In [1]:
import sys

print("Python version:", sys.version)

Python version: 3.12.4 | packaged by Anaconda, Inc. | (main, Jun 18 2024, 10:07:17) [Clang 14.0.6 ]

In [2]:
import importlib.util

libraries = [
    "pandas",
    "openpyxl",
    "folium",
    "streamlit",
    "ipywidgets",
    "requests"
]

for library in libraries:
    installed = importlib.util.find_spec(library) is not None
    print(f"{library}: {'Installed' if installed else 'Not installed'}")

pandas: Installed
openpyxl: Installed
folium: Installed
streamlit: Installed
ipywidgets: Installed
requests: Installed

In [3]:
%pip install folium streamlit streamlit-folium

Requirement already satisfied: folium in /opt/anaconda3/lib/python3.12/site-packages (0.20.0)
Requirement already satisfied: streamlit in /opt/anaconda3/lib/python3.12/site-packages (1.32.0)
Requirement already satisfied: streamlit-folium in /opt/anaconda3/lib/python3.12/site-packages (0.27.4)
Requirement already satisfied: branca>=0.6.0 in /opt/anaconda3/lib/python3.12/site-packages (from folium) (0.8.2)
Requirement already satisfied: jinja2>=2.9 in /opt/anaconda3/lib/python3.12/site-packages (from folium) (3.1.4)
Requirement already satisfied: numpy in /opt/anaconda3/lib/python3.12/site-packages (from folium) (1.26.4)
Requirement already satisfied: requests in /opt/anaconda3/lib/python3.12/site-packages (from folium) (2.32.2)
Requirement already satisfied: xyzservices in /opt/anaconda3/lib/python3.12/site-packages (from folium) (2022.9.0)
Requirement already satisfied: altair<6,>=4.0 in /opt/anaconda3/lib/python3.12/site-packages (from streamlit) (5.0.1)
Requirement already satisfied: blinker<2,>=1.0.0 in /opt/anaconda3/lib/python3.12/site-packages (from streamlit) (1.6.2)
Requirement already satisfied: cachetools<6,>=4.0 in /opt/anaconda3/lib/python3.12/site-packages (from streamlit) (5.3.3)
Requirement already satisfied: click<9,>=7.0 in /opt/anaconda3/lib/python3.12/site-packages (from streamlit) (8.1.7)
Requirement already satisfied: packaging<24,>=16.8 in /opt/anaconda3/lib/python3.12/site-packages (from streamlit) (23.2)
Requirement already satisfied: pandas<3,>=1.3.0 in /opt/anaconda3/lib/python3.12/site-packages (from streamlit) (2.2.2)
Requirement already satisfied: pillow<11,>=7.1.0 in /opt/anaconda3/lib/python3.12/site-packages (from streamlit) (10.3.0)
Requirement already satisfied: protobuf<5,>=3.20 in /opt/anaconda3/lib/python3.12/site-packages (from streamlit) (3.20.3)
Requirement already satisfied: pyarrow>=7.0 in /opt/anaconda3/lib/python3.12/site-packages (from streamlit) (14.0.2)
Requirement already satisfied: rich<14,>=10.14.0 in /opt/anaconda3/lib/python3.12/site-packages (from streamlit) (13.3.5)
Requirement already satisfied: tenacity<9,>=8.1.0 in /opt/anaconda3/lib/python3.12/site-packages (from streamlit) (8.2.2)
Requirement already satisfied: toml<2,>=0.10.1 in /opt/anaconda3/lib/python3.12/site-packages (from streamlit) (0.10.2)
Requirement already satisfied: typing-extensions<5,>=4.3.0 in /opt/anaconda3/lib/python3.12/site-packages (from streamlit) (4.11.0)
Requirement already satisfied: gitpython!=3.1.19,<4,>=3.0.7 in /opt/anaconda3/lib/python3.12/site-packages (from streamlit) (3.1.37)
Requirement already satisfied: pydeck<1,>=0.8.0b4 in /opt/anaconda3/lib/python3.12/site-packages (from streamlit) (0.8.0)
Requirement already satisfied: tornado<7,>=6.0.3 in /opt/anaconda3/lib/python3.12/site-packages (from streamlit) (6.4.1)
Requirement already satisfied: jsonschema>=3.0 in /opt/anaconda3/lib/python3.12/site-packages (from altair<6,>=4.0->streamlit) (4.19.2)
Requirement already satisfied: toolz in /opt/anaconda3/lib/python3.12/site-packages (from altair<6,>=4.0->streamlit) (0.12.0)
Requirement already satisfied: gitdb<5,>=4.0.1 in /opt/anaconda3/lib/python3.12/site-packages (from gitpython!=3.1.19,<4,>=3.0.7->streamlit) (4.0.7)
Requirement already satisfied: MarkupSafe>=2.0 in /opt/anaconda3/lib/python3.12/site-packages (from jinja2>=2.9->folium) (2.1.3)
Requirement already satisfied: python-dateutil>=2.8.2 in /opt/anaconda3/lib/python3.12/site-packages (from pandas<3,>=1.3.0->streamlit) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in /opt/anaconda3/lib/python3.12/site-packages (from pandas<3,>=1.3.0->streamlit) (2024.1)
Requirement already satisfied: tzdata>=2022.7 in /opt/anaconda3/lib/python3.12/site-packages (from pandas<3,>=1.3.0->streamlit) (2023.3)
Requirement already satisfied: charset-normalizer<4,>=2 in /opt/anaconda3/lib/python3.12/site-packages (from requests->folium) (2.0.4)
Requirement already satisfied: idna<4,>=2.5 in /opt/anaconda3/lib/python3.12/site-packages (from requests->folium) (3.7)
Requirement already satisfied: urllib3<3,>=1.21.1 in /opt/anaconda3/lib/python3.12/site-packages (from requests->folium) (2.2.2)
Requirement already satisfied: certifi>=2017.4.17 in /opt/anaconda3/lib/python3.12/site-packages (from requests->folium) (2024.7.4)
Requirement already satisfied: markdown-it-py<3.0.0,>=2.2.0 in /opt/anaconda3/lib/python3.12/site-packages (from rich<14,>=10.14.0->streamlit) (2.2.0)
Requirement already satisfied: pygments<3.0.0,>=2.13.0 in /opt/anaconda3/lib/python3.12/site-packages (from rich<14,>=10.14.0->streamlit) (2.15.1)
Requirement already satisfied: smmap<5,>=3.0.1 in /opt/anaconda3/lib/python3.12/site-packages (from gitdb<5,>=4.0.1->gitpython!=3.1.19,<4,>=3.0.7->streamlit) (4.0.0)
Requirement already satisfied: attrs>=22.2.0 in /opt/anaconda3/lib/python3.12/site-packages (from jsonschema>=3.0->altair<6,>=4.0->streamlit) (23.1.0)
Requirement already satisfied: jsonschema-specifications>=2023.03.6 in /opt/anaconda3/lib/python3.12/site-packages (from jsonschema>=3.0->altair<6,>=4.0->streamlit) (2023.7.1)
Requirement already satisfied: referencing>=0.28.4 in /opt/anaconda3/lib/python3.12/site-packages (from jsonschema>=3.0->altair<6,>=4.0->streamlit) (0.30.2)
Requirement already satisfied: rpds-py>=0.7.1 in /opt/anaconda3/lib/python3.12/site-packages (from jsonschema>=3.0->altair<6,>=4.0->streamlit) (0.10.6)
Requirement already satisfied: mdurl~=0.1 in /opt/anaconda3/lib/python3.12/site-packages (from markdown-it-py<3.0.0,>=2.2.0->rich<14,>=10.14.0->streamlit) (0.1.0)
Requirement already satisfied: six>=1.5 in /opt/anaconda3/lib/python3.12/site-packages (from python-dateutil>=2.8.2->pandas<3,>=1.3.0->streamlit) (1.16.0)
Note: you may need to restart the kernel to use updated packages.

In [4]:
import folium
import streamlit
import streamlit_folium

print("Folium version:", folium.__version__)
print("Streamlit version:", streamlit.__version__)
print("All required libraries installed successfully!")

Folium version: 0.20.0
Streamlit version: 1.32.0
All required libraries installed successfully!

In [5]:
import os

# Display the current working directory
print("Current working directory:", os.getcwd())

# Display all files and folders in the current directory
print("\nFiles and folders:")
for item in os.listdir():
    print("-", item)

Current working directory: /Users/khlee/Downloads/SDDProject6Week5/FullProject

Files and folders:
- VoyagePlannerUIDevelopment1.0.ipynb
- voyage_exports
- .ipynb_checkpoints
- voyage_planner_datasets_20261006.xlsx

In [6]:
# Display all files and folders in the current directory
print("\nFiles and folders:")
for item in os.listdir():
    print("-", item)

Files and folders:
- VoyagePlannerUIDevelopment1.0.ipynb
- voyage_exports
- .ipynb_checkpoints
- voyage_planner_datasets_20261006.xlsx

In [7]:
import pandas as pd

# Load the Excel workbook
file_path = "voyage_planner_datasets_20261006.xlsx"

excel_file = pd.ExcelFile(file_path)

# Display available worksheets
print("Available worksheets:")
for sheet in excel_file.sheet_names:
    print("-", sheet)

Available worksheets:
- Port Reference
- Passage Reference
- Synthetic Positions
- Benchmark Routes
- Data Sources

In [8]:
# Load the Port Reference worksheet
ports_df = pd.read_excel(
    file_path,
    sheet_name="Port Reference"
)

# Display dataset dimensions
print("Number of rows:", ports_df.shape[0])
print("Number of columns:", ports_df.shape[1])

# Display column names
print("\nColumn names:")
print(ports_df.columns.tolist())

# Preview the first five rows
display(ports_df.head())

Number of rows: 29
Number of columns: 16

Column names:
['port_id', 'port_name', 'un_locode', 'country', 'country_code', 'latitude', 'longitude', 'approach_latitude', 'approach_longitude', 'aliases', 'status', 'source', 'source_version', 'access_date', 'licence', 'notes']

,port_id,port_name,un_locode,country,country_code,latitude,longitude,approach_latitude,approach_longitude,aliases,status,source,source_version,access_date,licence,notes
0,SGSIN,Singapore,SGSIN,Singapore,SG,1.2644,103.82,1.2644,103.82,Singapore Port|PSA Singapore,active,NGA WPI; UN/LOCODE,2025-1,2026-09-15,Verify source terms,Initial port-level point; refine during routin...
1,USHOU,Houston,USHOU,United States,US,29.7300,-95.00,29.7300,-95.00,Port of Houston,active,NGA WPI; UN/LOCODE,2025-1,2026-09-15,Verify source terms,Initial port-level point; refine during routin...
2,NLRTM,Rotterdam,NLRTM,Netherlands,NL,51.9500,4.14,51.9500,4.14,Port of Rotterdam,active,NGA WPI; UN/LOCODE,2025-1,2026-09-15,Verify source terms,Initial port-level point; refine during routin...
3,ZADUR,Durban,ZADUR,South Africa,ZA,-29.8700,31.05,-29.8700,31.05,Port of Durban,active,NGA WPI; UN/LOCODE,2025-1,2026-09-15,Verify source terms,Initial port-level point; refine during routin...
4,CLTOQ,Tocopilla,CLTOQ,Chile,CL,-22.0900,-70.20,-22.0900,-70.20,Puerto Tocopilla,active,NGA WPI; UN/LOCODE,2025-1,2026-09-15,Verify source terms,Initial port-level point; refine during routin...

In [9]:
# Filter active ports
active_ports = ports_df[
    ports_df["status"].str.lower() == "active"
].copy()

# Select relevant columns
active_ports = active_ports[
    [
        "port_id",
        "port_name",
        "country",
        "latitude",
        "longitude",
        "approach_latitude",
        "approach_longitude"
    ]
]

# Sort ports alphabetically
active_ports = active_ports.sort_values("port_name")

# Reset index
active_ports = active_ports.reset_index(drop=True)

# Display results
print("Number of active ports:", len(active_ports))

display(active_ports)

Number of active ports: 29

,port_id,port_name,country,latitude,longitude,approach_latitude,approach_longitude
0,ESALG,Algeciras,Spain,36.1300,-5.44,36.1300,-5.44
1,BEANR,Antwerp,Belgium,51.2600,4.40,51.2600,4.40
2,ARBUE,Buenos Aires,Argentina,-34.6000,-58.37,-34.6000,-58.37
3,PECLL,Callao,Peru,-12.0500,-77.15,-12.0500,-77.15
4,ZACPT,Cape Town,South Africa,-33.9200,18.43,-33.9200,18.43
5,LKCMB,Colombo,Sri Lanka,6.9500,79.85,6.9500,79.85
6,PAMIT,Colon,Panama,9.3600,-79.90,9.3600,-79.90
7,ZADUR,Durban,South Africa,-29.8700,31.05,-29.8700,31.05
8,AUFRE,Fremantle,Australia,-32.0500,115.74,-32.0500,115.74
9,AEFJR,Fujairah,United Arab Emirates,25.1200,56.36,25.1200,56.36
10,GIIBZ,Gibraltar,Gibraltar,36.1400,-5.35,36.1400,-5.35
11,DEHAM,Hamburg,Germany,53.5400,9.97,53.5400,9.97
12,HKHKG,Hong Kong,Hong Kong,22.2900,114.17,22.2900,114.17
13,USHOU,Houston,United States,29.7300,-95.00,29.7300,-95.00
14,AUMEL,Melbourne,Australia,-37.8400,144.92,-37.8400,144.92
15,INBOM,Mumbai,India,18.9400,72.84,18.9400,72.84
16,USNYC,New York,United States,40.6800,-74.04,40.6800,-74.04
17,PAPTY,Panama City,Panama,8.9500,-79.53,8.9500,-79.53
18,EGPSD,Port Said,Egypt,31.2600,32.30,31.2600,32.30
19,ZARCB,Richards Bay,South Africa,-28.8000,32.04,-28.8000,32.04
20,BRRIO,Rio de Janeiro,Brazil,-22.9000,-43.17,-22.9000,-43.17
21,NLRTM,Rotterdam,Netherlands,51.9500,4.14,51.9500,4.14
22,BRSSZ,Santos,Brazil,-23.9600,-46.33,-23.9600,-46.33
23,CNSHA,Shanghai,China,31.2300,121.49,31.2300,121.49
24,SGSIN,Singapore,Singapore,1.2644,103.82,1.2644,103.82
25,EGSUZ,Suez,Egypt,29.9500,32.55,29.9500,32.55
26,AUSYD,Sydney,Australia,-33.8500,151.20,-33.8500,151.20
27,CLTOQ,Tocopilla,Chile,-22.0900,-70.20,-22.0900,-70.20
28,CLVAP,Valparaiso,Chile,-33.0400,-71.63,-33.0400,-71.63

In [10]:
import ipywidgets as widgets
from IPython.display import display

# Create a list of ports for dropdown selection
port_options = [
    (f"{row['port_name']} ({row['country']})", row["port_id"])
    for _, row in active_ports.iterrows()
]

# Create origin port dropdown
origin_dropdown = widgets.Dropdown(
    options=port_options,
    description="Origin:",
    style={"description_width": "initial"},
    layout=widgets.Layout(width="400px")
)

# Create destination port dropdown
destination_dropdown = widgets.Dropdown(
    options=port_options,
    description="Destination:",
    style={"description_width": "initial"},
    layout=widgets.Layout(width="400px")
)

# Display dropdowns
display(origin_dropdown, destination_dropdown)

Dropdown(description='Origin:', layout=Layout(width='400px'), options=(('Algeciras (Spain)', 'ESALG'), ('Antwe…

Dropdown(description='Destination:', layout=Layout(width='400px'), options=(('Algeciras (Spain)', 'ESALG'), ('…

In [11]:
# Retrieve selected ports
origin_id = origin_dropdown.value
destination_id = destination_dropdown.value

# Display selections
origin_port = active_ports[
    active_ports["port_id"] == origin_id
].iloc[0]

destination_port = active_ports[
    active_ports["port_id"] == destination_id
].iloc[0]

print("Origin:", origin_port["port_name"])
print("Destination:", destination_port["port_name"])

print("\nOrigin coordinates:")
print(origin_port["approach_latitude"], origin_port["approach_longitude"])

print("\nDestination coordinates:")
print(destination_port["approach_latitude"], destination_port["approach_longitude"])

Origin: Algeciras
Destination: Algeciras

Origin coordinates:
36.13 -5.44

Destination coordinates:
36.13 -5.44

In [12]:
import ipywidgets as widgets
from IPython.display import display, clear_output

# Create Calculate Route button
calculate_button = widgets.Button(
    description="Calculate Route",
    button_style="primary",
    icon="ship",
    layout=widgets.Layout(width="200px")
)

# Create output area
route_output = widgets.Output()

# Define button functionality
def calculate_route_clicked(button):
    with route_output:
        clear_output(wait=True)

        origin_id = origin_dropdown.value
        destination_id = destination_dropdown.value

        # Validate selections
        if origin_id == destination_id:
            print("Error: Origin and destination cannot be the same.")
            return

        # Retrieve selected ports
        origin = active_ports[
            active_ports["port_id"] == origin_id
        ].iloc[0]

        destination = active_ports[
            active_ports["port_id"] == destination_id
        ].iloc[0]

        # Display route information
        print("VOYAGE PLANNER — ROUTE INFORMATION")
        print("----------------------------------")
        print("Origin:", origin["port_name"])
        print("Destination:", destination["port_name"])

        print("\nOrigin coordinates:")
        print(origin["approach_latitude"], origin["approach_longitude"])

        print("\nDestination coordinates:")
        print(destination["approach_latitude"], destination["approach_longitude"])

        print("\nRoute calculation: Not yet connected.")

# Connect button to function
calculate_button.on_click(calculate_route_clicked)

# Display button and output
display(calculate_button, route_output)

Button(button_style='primary', description='Calculate Route', icon='ship', layout=Layout(width='200px'), style…

Output()

In [13]:
import folium
from IPython.display import display

# Retrieve currently selected ports
origin_id = origin_dropdown.value
destination_id = destination_dropdown.value

origin = active_ports[
    active_ports["port_id"] == origin_id
].iloc[0]

destination = active_ports[
    active_ports["port_id"] == destination_id
].iloc[0]

# Extract coordinates
origin_coords = [
    float(origin["approach_latitude"]),
    float(origin["approach_longitude"])
]

destination_coords = [
    float(destination["approach_latitude"]),
    float(destination["approach_longitude"])
]

# Create interactive map
voyage_map = folium.Map(
    location=[20, 40],
    zoom_start=2,
    tiles="OpenStreetMap"
)

# Add origin marker
folium.Marker(
    location=origin_coords,
    popup=f"Origin: {origin['port_name']}",
    tooltip=f"Origin: {origin['port_name']}",
    icon=folium.Icon(color="green", icon="play")
).add_to(voyage_map)

# Add destination marker
folium.Marker(
    location=destination_coords,
    popup=f"Destination: {destination['port_name']}",
    tooltip=f"Destination: {destination['port_name']}",
    icon=folium.Icon(color="red", icon="flag")
).add_to(voyage_map)

# Automatically adjust map to show both ports
voyage_map.fit_bounds([
    origin_coords,
    destination_coords
])

# Display map
display(voyage_map)

In [14]:
%pip install searoute

Requirement already satisfied: searoute in /opt/anaconda3/lib/python3.12/site-packages (1.6.0)
Requirement already satisfied: geojson in /opt/anaconda3/lib/python3.12/site-packages (from searoute) (3.3.0)
Requirement already satisfied: networkx in /opt/anaconda3/lib/python3.12/site-packages (from searoute) (3.2.1)
Note: you may need to restart the kernel to use updated packages.

In [15]:
import searoute as sr

print("searoute imported successfully!")

searoute imported successfully!

In [16]:
import searoute as sr

# Retrieve selected ports
origin_id = origin_dropdown.value
destination_id = destination_dropdown.value

origin = active_ports[
    active_ports["port_id"] == origin_id
].iloc[0]

destination = active_ports[
    active_ports["port_id"] == destination_id
].iloc[0]

# Convert coordinates to searoute format: [longitude, latitude]
origin_searoute = [
    float(origin["approach_longitude"]),
    float(origin["approach_latitude"])
]

destination_searoute = [
    float(destination["approach_longitude"]),
    float(destination["approach_latitude"])
]

# Calculate maritime route
route = sr.searoute(
    origin_searoute,
    destination_searoute,
    units="naut"
)

# Extract route information
route_distance = route.properties["length"]
route_coordinates = route.geometry["coordinates"]

# Display results
print("VOYAGE PLANNER — MARITIME ROUTE")
print("--------------------------------")
print("Origin:", origin["port_name"])
print("Destination:", destination["port_name"])
print(f"Maritime distance: {route_distance:,.2f} nautical miles")
print("Number of route coordinates:", len(route_coordinates))

VOYAGE PLANNER — MARITIME ROUTE
--------------------------------
Origin: Algeciras
Destination: Algeciras
Maritime distance: 0.00 nautical miles
Number of route coordinates: 1

In [17]:
import folium
from IPython.display import display

# Create interactive maritime map
route_map = folium.Map(
    location=[20, 115],
    zoom_start=4,
    tiles="OpenStreetMap"
)

# Convert searoute coordinates [longitude, latitude]
# to Folium coordinates [latitude, longitude]
folium_route_coordinates = [
    [lat, lon]
    for lon, lat in route_coordinates
]

# Draw calculated maritime route
folium.PolyLine(
    locations=folium_route_coordinates,
    color="blue",
    weight=4,
    opacity=0.8,
    tooltip=f"Maritime distance: {route_distance:,.2f} NM"
).add_to(route_map)

# Add origin marker
folium.Marker(
    location=[
        float(origin["approach_latitude"]),
        float(origin["approach_longitude"])
    ],
    popup=f"Origin: {origin['port_name']}",
    tooltip=f"Origin: {origin['port_name']}",
    icon=folium.Icon(color="green", icon="play")
).add_to(route_map)

# Add destination marker
folium.Marker(
    location=[
        float(destination["approach_latitude"]),
        float(destination["approach_longitude"])
    ],
    popup=f"Destination: {destination['port_name']}",
    tooltip=f"Destination: {destination['port_name']}",
    icon=folium.Icon(color="red", icon="flag")
).add_to(route_map)

# Automatically fit the map to the route
route_map.fit_bounds(folium_route_coordinates)

# Display interactive map
display(route_map)

In [18]:
import ipywidgets as widgets
import folium
import searoute as sr

from IPython.display import display, clear_output

# Create Calculate Route button
integrated_button = widgets.Button(
    description="Calculate Route",
    button_style="primary",
    icon="ship",
    layout=widgets.Layout(width="200px")
)

# Create output area
integrated_output = widgets.Output()

# Define calculation function
def calculate_integrated_route(button):

    with integrated_output:

        clear_output(wait=True)

        try:
            # Retrieve selected ports
            origin_id = origin_dropdown.value
            destination_id = destination_dropdown.value

            # Validate selection
            if origin_id == destination_id:
                print("Error: Origin and destination cannot be the same.")
                return

            origin = active_ports[
                active_ports["port_id"] == origin_id
            ].iloc[0]

            destination = active_ports[
                active_ports["port_id"] == destination_id
            ].iloc[0]

            # Convert coordinates to searoute format
            origin_coords = [
                float(origin["approach_longitude"]),
                float(origin["approach_latitude"])
            ]

            destination_coords = [
                float(destination["approach_longitude"]),
                float(destination["approach_latitude"])
            ]

            # Calculate maritime route
            route = sr.searoute(
                origin_coords,
                destination_coords,
                units="naut"
            )

            route_distance = route.properties["length"]
            route_coordinates = route.geometry["coordinates"]

            # Display route information
            print("VOYAGE PLANNER — ROUTE RESULTS")
            print("--------------------------------")
            print("Origin:", origin["port_name"])
            print("Destination:", destination["port_name"])
            print(f"Maritime distance: {route_distance:,.2f} NM")
            print(f"Route coordinates: {len(route_coordinates)}")

            # Convert coordinates for Folium
            folium_coordinates = [
                [lat, lon]
                for lon, lat in route_coordinates
            ]

            # Create map
            route_map = folium.Map(
                location=folium_coordinates[0],
                zoom_start=3,
                tiles="OpenStreetMap"
            )

            # Draw maritime route
            folium.PolyLine(
                locations=folium_coordinates,
                color="blue",
                weight=4,
                opacity=0.8,
                tooltip=f"{route_distance:,.2f} NM"
            ).add_to(route_map)

            # Add origin marker
            folium.Marker(
                location=[origin_coords[1], origin_coords[0]],
                popup=f"Origin: {origin['port_name']}",
                icon=folium.Icon(color="green", icon="play")
            ).add_to(route_map)

            # Add destination marker
            folium.Marker(
                location=[destination_coords[1], destination_coords[0]],
                popup=f"Destination: {destination['port_name']}",
                icon=folium.Icon(color="red", icon="flag")
            ).add_to(route_map)

            # Automatically adjust map view
            route_map.fit_bounds(folium_coordinates)

            # Display map
            display(route_map)

        except Exception as error:
            print("Route calculation failed.")
            print("Error details:", error)


# Connect button to calculation function
integrated_button.on_click(calculate_integrated_route)

# Display complete interface
display(
    origin_dropdown,
    destination_dropdown,
    integrated_button,
    integrated_output
)

Dropdown(description='Origin:', layout=Layout(width='400px'), options=(('Algeciras (Spain)', 'ESALG'), ('Antwe…

Dropdown(description='Destination:', layout=Layout(width='400px'), options=(('Algeciras (Spain)', 'ESALG'), ('…

Button(button_style='primary', description='Calculate Route', icon='ship', layout=Layout(width='200px'), style…

Output()

In [19]:
# Create vessel speed input
speed_input = widgets.BoundedFloatText(
    value=15.0,
    min=1.0,
    max=40.0,
    step=0.5,
    description="Vessel Speed (knots):",
    style={"description_width": "initial"},
    layout=widgets.Layout(width="300px")
)

display(speed_input)

BoundedFloatText(value=15.0, description='Vessel Speed (knots):', layout=Layout(width='300px'), max=40.0, min=…

In [20]:
# Retrieve vessel speed
vessel_speed = speed_input.value

# Calculate estimated sailing duration
voyage_hours = route_distance / vessel_speed
voyage_days = voyage_hours / 24

print("VOYAGE PLANNER — VOYAGE ESTIMATE")
print("--------------------------------")
print(f"Maritime distance: {route_distance:,.2f} NM")
print(f"Vessel speed: {vessel_speed:.1f} knots")
print(f"Estimated sailing time: {voyage_hours:.2f} hours")
print(f"Estimated sailing duration: {voyage_days:.2f} days")

VOYAGE PLANNER — VOYAGE ESTIMATE
--------------------------------
Maritime distance: 0.00 NM
Vessel speed: 15.0 knots
Estimated sailing time: 0.00 hours
Estimated sailing duration: 0.00 days

In [21]:
import ipywidgets as widgets
import folium
import searoute as sr

from IPython.display import display, clear_output

# Create a new Calculate Route button
voyage_button = widgets.Button(
    description="Calculate Route",
    button_style="primary",
    icon="ship",
    layout=widgets.Layout(width="200px")
)

# Create output area
voyage_output = widgets.Output()

# Define voyage calculation function
def calculate_voyage(button):

    with voyage_output:

        clear_output(wait=True)

        try:
            # Retrieve user selections
            origin_id = origin_dropdown.value
            destination_id = destination_dropdown.value
            vessel_speed = speed_input.value

            # Validate inputs
            if origin_id == destination_id:
                print("Error: Origin and destination cannot be the same.")
                return

            if vessel_speed <= 0:
                print("Error: Vessel speed must be greater than zero.")
                return

            # Retrieve port information
            origin = active_ports[
                active_ports["port_id"] == origin_id
            ].iloc[0]

            destination = active_ports[
                active_ports["port_id"] == destination_id
            ].iloc[0]

            # Convert coordinates to searoute format
            origin_coords = [
                float(origin["approach_longitude"]),
                float(origin["approach_latitude"])
            ]

            destination_coords = [
                float(destination["approach_longitude"]),
                float(destination["approach_latitude"])
            ]

            # Calculate maritime route
            route = sr.searoute(
                origin_coords,
                destination_coords,
                units="naut"
            )

            route_distance = route.properties["length"]
            route_coordinates = route.geometry["coordinates"]

            # Calculate estimated voyage duration
            voyage_hours = route_distance / vessel_speed
            voyage_days = voyage_hours / 24

            # Display voyage summary
            print("VOYAGE PLANNER — VOYAGE SUMMARY")
            print("--------------------------------")
            print(f"Origin: {origin['port_name']}")
            print(f"Destination: {destination['port_name']}")
            print(f"Maritime distance: {route_distance:,.2f} NM")
            print(f"Vessel speed: {vessel_speed:.1f} knots")
            print(f"Estimated sailing time: {voyage_hours:.2f} hours")
            print(f"Estimated sailing duration: {voyage_days:.2f} days")

            # Convert coordinates for Folium
            folium_coordinates = [
                [lat, lon]
                for lon, lat in route_coordinates
            ]

            # Create interactive map
            voyage_map = folium.Map(
                location=folium_coordinates[0],
                zoom_start=3,
                tiles="OpenStreetMap"
            )

            # Draw maritime route
            folium.PolyLine(
                locations=folium_coordinates,
                color="blue",
                weight=4,
                opacity=0.8,
                tooltip=f"{route_distance:,.2f} NM"
            ).add_to(voyage_map)

            # Add origin marker
            folium.Marker(
                location=[origin_coords[1], origin_coords[0]],
                popup=f"Origin: {origin['port_name']}",
                tooltip=f"Origin: {origin['port_name']}",
                icon=folium.Icon(color="green", icon="play")
            ).add_to(voyage_map)

            # Add destination marker
            folium.Marker(
                location=[destination_coords[1], destination_coords[0]],
                popup=f"Destination: {destination['port_name']}",
                tooltip=f"Destination: {destination['port_name']}",
                icon=folium.Icon(color="red", icon="flag")
            ).add_to(voyage_map)

            # Fit map to route
            voyage_map.fit_bounds(folium_coordinates)

            # Display map
            display(voyage_map)

        except Exception as error:
            print("Voyage calculation failed.")
            print("Error details:", error)


# Connect button to calculation function
voyage_button.on_click(calculate_voyage)

# Display unified interface
display(
    widgets.HTML("<h2>Maritime Voyage Planner</h2>"),
    origin_dropdown,
    destination_dropdown,
    speed_input,
    voyage_button,
    voyage_output
)

HTML(value='<h2>Maritime Voyage Planner</h2>')

Dropdown(description='Origin:', layout=Layout(width='400px'), options=(('Algeciras (Spain)', 'ESALG'), ('Antwe…

Dropdown(description='Destination:', layout=Layout(width='400px'), options=(('Algeciras (Spain)', 'ESALG'), ('…

BoundedFloatText(value=15.0, description='Vessel Speed (knots):', layout=Layout(width='300px'), max=40.0, min=…

Button(button_style='primary', description='Calculate Route', icon='ship', layout=Layout(width='200px'), style…

Output()

In [22]:
# Create multi-stop port selector
multi_stop_selector = widgets.SelectMultiple(
    options=port_options,
    description="Voyage Stops:",
    rows=10,
    style={"description_width": "initial"},
    layout=widgets.Layout(width="450px")
)

display(multi_stop_selector)

SelectMultiple(description='Voyage Stops:', layout=Layout(width='450px'), options=(('Algeciras (Spain)', 'ESAL…

In [23]:
import ipywidgets as widgets
from IPython.display import display, clear_output

# Store the ordered list of selected ports
voyage_stops = []

# Port selection dropdown
stop_dropdown = widgets.Dropdown(
    options=port_options,
    description="Select Port:",
    style={"description_width": "initial"},
    layout=widgets.Layout(width="400px")
)

# Buttons
add_stop_button = widgets.Button(
    description="Add Stop",
    button_style="success",
    icon="plus"
)

remove_stop_button = widgets.Button(
    description="Remove Last Stop",
    button_style="warning",
    icon="minus"
)

clear_stops_button = widgets.Button(
    description="Clear All",
    button_style="danger",
    icon="trash"
)

# Output area
itinerary_output = widgets.Output()

# Display current itinerary
def display_itinerary():

    with itinerary_output:
        clear_output(wait=True)

        print("VOYAGE PLANNER — ITINERARY")
        print("--------------------------")

        if not voyage_stops:
            print("No ports selected.")
            return

        for index, port_id in enumerate(voyage_stops, start=1):

            port = active_ports[
                active_ports["port_id"] == port_id
            ].iloc[0]

            print(f"{index}. {port['port_name']}")

# Add stop
def add_stop_clicked(button):

    selected_port = stop_dropdown.value

    if voyage_stops and voyage_stops[-1] == selected_port:
        with itinerary_output:
            clear_output(wait=True)
            print("Error: Consecutive stops cannot be the same port.")
        return

    voyage_stops.append(selected_port)

    display_itinerary()

# Remove last stop
def remove_stop_clicked(button):

    if voyage_stops:
        voyage_stops.pop()

    display_itinerary()

# Clear itinerary
def clear_stops_clicked(button):

    voyage_stops.clear()

    display_itinerary()

# Connect buttons
add_stop_button.on_click(add_stop_clicked)
remove_stop_button.on_click(remove_stop_clicked)
clear_stops_button.on_click(clear_stops_clicked)

# Display interface
display(
    widgets.HTML("<h3>Multi-Leg Voyage Planner</h3>"),
    stop_dropdown,
    widgets.HBox([
        add_stop_button,
        remove_stop_button,
        clear_stops_button
    ]),
    itinerary_output
)

display_itinerary()

HTML(value='<h3>Multi-Leg Voyage Planner</h3>')

Dropdown(description='Select Port:', layout=Layout(width='400px'), options=(('Algeciras (Spain)', 'ESALG'), ('…

HBox(children=(Button(button_style='success', description='Add Stop', icon='plus', style=ButtonStyle()), Butto…

Output()

In [26]:
import searoute as sr
import pandas as pd

# Ensure at least two ports are selected
if len(voyage_stops) < 2:
    print("Error: Please select at least two ports.")

else:
    # Store individual leg results
    leg_results = []

    # Calculate each voyage leg
    for i in range(len(voyage_stops) - 1):

        origin_id = voyage_stops[i]
        destination_id = voyage_stops[i + 1]

        # Retrieve port information
        origin = active_ports[
            active_ports["port_id"] == origin_id
        ].iloc[0]

        destination = active_ports[
            active_ports["port_id"] == destination_id
        ].iloc[0]

        # Convert coordinates to searoute format
        origin_coords = [
            float(origin["approach_longitude"]),
            float(origin["approach_latitude"])
        ]

        destination_coords = [
            float(destination["approach_longitude"]),
            float(destination["approach_latitude"])
        ]

        # Calculate maritime route
        route = sr.searoute(
            origin_coords,
            destination_coords,
            units="naut"
        )

        # Extract distance
        distance = route.properties["length"]

        # Store leg information
        leg_results.append({
            "Leg": i + 1,
            "Origin": origin["port_name"],
            "Destination": destination["port_name"],
            "Distance (NM)": distance,
            "Coordinates": route.geometry["coordinates"]
        })

    # Calculate total maritime distance
    total_distance = sum(
        leg["Distance (NM)"] for leg in leg_results
    )

    # Retrieve vessel speed
    vessel_speed = speed_input.value

    # Calculate estimated sailing duration
    total_hours = total_distance / vessel_speed
    total_days = total_hours / 24

    # Display results
    print("VOYAGE PLANNER — MULTI-LEG RESULTS")
    print("----------------------------------")

    # Create results table without geometry
    results_df = pd.DataFrame([
        {
            "Leg": leg["Leg"],
            "Origin": leg["Origin"],
            "Destination": leg["Destination"],
            "Distance (NM)": round(leg["Distance (NM)"], 2)
        }
        for leg in leg_results
    ])

    display(results_df)

    print(f"\nTotal maritime distance: {total_distance:,.2f} NM")
    print(f"Vessel speed: {vessel_speed:.1f} knots")
    print(f"Estimated sailing time: {total_hours:.2f} hours")
    print(f"Estimated sailing duration: {total_days:.2f} days")

VOYAGE PLANNER — MULTI-LEG RESULTS
----------------------------------

   Leg     Origin Destination  Distance (NM)
0    1  Singapore    Shanghai        2213.54

Total maritime distance: 2,213.54 NM
Vessel speed: 15.0 knots
Estimated sailing time: 147.57 hours
Estimated sailing duration: 6.15 days

In [28]:
import folium
from IPython.display import display

# Create interactive map
multi_leg_map = folium.Map(
    location=[20, 60],
    zoom_start=2,
    tiles="OpenStreetMap"
)

# Assign different colors to each leg
leg_colors = [
    "blue", "green", "purple",
    "orange", "red", "darkblue"
]

# Store all coordinates for map positioning
all_route_coordinates = []

# Draw each maritime leg
for index, leg in enumerate(leg_results):

    # Convert searoute coordinates to Folium format
    coordinates = [
        [lat, lon]
        for lon, lat in leg["Coordinates"]
    ]

    all_route_coordinates.extend(coordinates)

    # Select color
    color = leg_colors[index % len(leg_colors)]

    # Draw route
    folium.PolyLine(
        locations=coordinates,
        color=color,
        weight=4,
        opacity=0.85,
        tooltip=(
            f"Leg {leg['Leg']}: "
            f"{leg['Origin']} → {leg['Destination']} "
            f"({leg['Distance (NM)']:,.2f} NM)"
        )
    ).add_to(multi_leg_map)

# Add numbered port markers
for index, port_id in enumerate(voyage_stops):

    port = active_ports[
        active_ports["port_id"] == port_id
    ].iloc[0]

    port_coordinates = [
        float(port["approach_latitude"]),
        float(port["approach_longitude"])
    ]

    # Determine marker color
    if index == 0:
        marker_color = "green"
    elif index == len(voyage_stops) - 1:
        marker_color = "red"
    else:
        marker_color = "blue"

    # Add numbered marker
    folium.Marker(
        location=port_coordinates,
        popup=(
            f"Stop {index + 1}: "
            f"{port['port_name']}"
        ),
        tooltip=(
            f"{index + 1}. "
            f"{port['port_name']}"
        ),
        icon=folium.Icon(
            color=marker_color,
            icon="info-sign"
        )
    ).add_to(multi_leg_map)

# Automatically fit map to all routes
multi_leg_map.fit_bounds(all_route_coordinates)

# Display map
display(multi_leg_map)

In [30]:
import ipywidgets as widgets
import folium
import searoute as sr
import pandas as pd

from IPython.display import display, clear_output

# Create button
multi_leg_button = widgets.Button(
    description="Calculate Voyage",
    button_style="primary",
    icon="ship",
    layout=widgets.Layout(width="200px")
)

# Create output area
multi_leg_output = widgets.Output()

def calculate_multi_leg_voyage(button):

    with multi_leg_output:
        clear_output(wait=True)

        try:
            # Validate itinerary
            if len(voyage_stops) < 2:
                print("Error: Please add at least two ports.")
                return

            # Retrieve vessel speed
            vessel_speed = speed_input.value

            if vessel_speed <= 0:
                print("Error: Vessel speed must be greater than zero.")
                return

            # Store results
            leg_results = []

            # Calculate each leg
            for i in range(len(voyage_stops) - 1):

                origin_id = voyage_stops[i]
                destination_id = voyage_stops[i + 1]

                origin = active_ports[
                    active_ports["port_id"] == origin_id
                ].iloc[0]

                destination = active_ports[
                    active_ports["port_id"] == destination_id
                ].iloc[0]

                origin_coords = [
                    float(origin["approach_longitude"]),
                    float(origin["approach_latitude"])
                ]

                destination_coords = [
                    float(destination["approach_longitude"]),
                    float(destination["approach_latitude"])
                ]

                # Calculate maritime route
                route = sr.searoute(
                    origin_coords,
                    destination_coords,
                    units="naut"
                )

                leg_results.append({
                    "Leg": i + 1,
                    "Origin": origin["port_name"],
                    "Destination": destination["port_name"],
                    "Distance (NM)": route.properties["length"],
                    "Coordinates": route.geometry["coordinates"]
                })

            # Calculate totals
            total_distance = sum(
                leg["Distance (NM)"]
                for leg in leg_results
            )

            total_hours = total_distance / vessel_speed
            total_days = total_hours / 24

            # Display results
            print("VOYAGE PLANNER — MULTI-LEG SUMMARY")
            print("-----------------------------------")

            results_df = pd.DataFrame([
                {
                    "Leg": leg["Leg"],
                    "Origin": leg["Origin"],
                    "Destination": leg["Destination"],
                    "Distance (NM)": round(leg["Distance (NM)"], 2)
                }
                for leg in leg_results
            ])

            display(results_df)

            print(f"\nTotal distance: {total_distance:,.2f} NM")
            print(f"Vessel speed: {vessel_speed:.1f} knots")
            print(f"Estimated sailing time: {total_hours:.2f} hours")
            print(f"Estimated sailing duration: {total_days:.2f} days")

            # Create map
            voyage_map = folium.Map(
                location=[20, 60],
                zoom_start=2,
                tiles="OpenStreetMap"
            )

            leg_colors = [
                "blue", "green", "purple",
                "orange", "red", "darkblue"
            ]

            all_coordinates = []

            # Draw each leg
            for index, leg in enumerate(leg_results):

                coordinates = [
                    [lat, lon]
                    for lon, lat in leg["Coordinates"]
                ]

                all_coordinates.extend(coordinates)

                folium.PolyLine(
                    locations=coordinates,
                    color=leg_colors[index % len(leg_colors)],
                    weight=4,
                    opacity=0.85,
                    tooltip=(
                        f"Leg {leg['Leg']}: "
                        f"{leg['Origin']} → {leg['Destination']} "
                        f"({leg['Distance (NM)']:,.2f} NM)"
                    )
                ).add_to(voyage_map)

            # Add port markers
            for index, port_id in enumerate(voyage_stops):

                port = active_ports[
                    active_ports["port_id"] == port_id
                ].iloc[0]

                coordinates = [
                    float(port["approach_latitude"]),
                    float(port["approach_longitude"])
                ]

                if index == 0:
                    marker_color = "green"
                elif index == len(voyage_stops) - 1:
                    marker_color = "red"
                else:
                    marker_color = "blue"

                folium.Marker(
                    location=coordinates,
                    popup=f"Stop {index + 1}: {port['port_name']}",
                    tooltip=f"{index + 1}. {port['port_name']}",
                    icon=folium.Icon(
                        color=marker_color,
                        icon="info-sign"
                    )
                ).add_to(voyage_map)

            # Adjust map view
            voyage_map.fit_bounds(all_coordinates)

            # Display map
            display(voyage_map)

        except Exception as error:
            print("Multi-leg voyage calculation failed.")
            print("Error details:", error)


# Connect button
multi_leg_button.on_click(calculate_multi_leg_voyage)

# Display calculation controls
display(
    widgets.HTML("<h3>Multi-Leg Voyage Calculation</h3>"),
    speed_input,
    multi_leg_button,
    multi_leg_output
)

HTML(value='<h3>Multi-Leg Voyage Calculation</h3>')

BoundedFloatText(value=15.0, description='Vessel Speed (knots):', layout=Layout(width='300px'), max=40.0, min=…

Button(button_style='primary', description='Calculate Voyage', icon='ship', layout=Layout(width='200px'), styl…

Output()

In [32]:
import ipywidgets as widgets
from IPython.display import display

passage_dropdown = widgets.Dropdown(
    options=[
        ("Automatic — Shortest Available Route", "automatic"),
        ("Via Suez Canal", "suez"),
        ("Via Panama Canal", "panama"),
        ("Via Cape of Good Hope", "cape_good_hope")
    ],
    value="automatic",
    description="Passage Preference:",
    style={"description_width": "initial"},
    layout=widgets.Layout(width="450px")
)

display(
    widgets.HTML("<h3>Maritime Passage Preferences</h3>"),
    passage_dropdown
)

HTML(value='<h3>Maritime Passage Preferences</h3>')

Dropdown(description='Passage Preference:', layout=Layout(width='450px'), options=(('Automatic — Shortest Avai…

In [34]:
import searoute as sr
import inspect

print("SEAROUTE FUNCTION SIGNATURE")
print("---------------------------")

print(inspect.signature(sr.searoute))

print("\nSEAROUTE DOCUMENTATION")
print("----------------------")

print(inspect.getdoc(sr.searoute))

SEAROUTE FUNCTION SIGNATURE
---------------------------
(origin, destination, units='km', speed_knot=24, append_orig_dest=False, restrictions=['northwest'], include_ports=False, port_params={}, M: searoute.classes.marnet.Marnet = None, P: searoute.classes.ports.Ports = None, return_passages: bool = False, algorithm=None, backend='networkx')

SEAROUTE DOCUMENTATION
----------------------
Calculates the shortest sea route between two points on Earth.

Parameters
----------
origin : a point as array lon, lat format ex. [0.35156, 50.06419]
destination : a point as array lon, lat format ex. [117.42187, 39.36827]
units : default is `km` = kilometers,
    can be `m` = meters `mi` = miles `ft` = foot
    `in` = inches `deg` = degrees `cen` = centimeters
    `rad` = radians `naut` = nautical `yd` = yards
speed_knot : speed of the boat, default is `24` knots
append_orig_dest : add origin and dest geo-points in the LineString of the route, default is False
restrictions : an list of restrictions of paths to avoid, use as per your specific need; default restricted ['northwest']; possible passages: babalmandab, bosporus, gibraltar, suez, panama, ormuz, northwest
include_ports : boolean to include closest port close to origin or destinations
port_params : object ;
    - only_terminals: boolean, default False
    - country_pol: country iso code for port of load
    - country_pod: country iso code for port of discharge
    - country_restricted :  boolean or 'strict', default False ; if True it will consider `country_pod` as a parameter to match with `to_cty` in ports list
                            if set to 'strict' then if will force ALL queries to match
    - ports_in_areas : a FeatureCollection containing areas with preferred ports, created of AreaFeature, use AreaFeature.create([...]). The previous configurations will be ignored.
                        If there are many ports then the result will be a list of GeoJson Features, instead of an object of GeoJson Feature.
                        Preferred ports with share = 0 will be ignored.
return_passages : boolean to return traversed passages (default is `False`)
algorithm : str one of `dijkstra` or `astar`, default `dijkstra`
backend : str one of `networkx` or `igraph`, default `networkx` chose between backend graph class

Returns
-------
a Feature (geojson) of a LineString of sea route with parameters : `unit` and `length`, `duration_hours` or port details, others

In [36]:
import searoute as sr

# Singapore coordinates [longitude, latitude]
singapore = [103.82, 1.2644]

# Rotterdam coordinates [longitude, latitude]
rotterdam = [4.14, 51.95]

# Route A: Default routing
route_default = sr.searoute(
    singapore,
    rotterdam,
    units="naut",
    return_passages=True
)

# Route B: Restrict Suez Canal
route_avoid_suez = sr.searoute(
    singapore,
    rotterdam,
    units="naut",
    restrictions=["suez"],
    return_passages=True
)

# Extract distances
distance_default = route_default.properties["length"]
distance_avoid_suez = route_avoid_suez.properties["length"]

# Display results
print("VOYAGE PLANNER — PASSAGE COMPARISON")
print("-----------------------------------")

print("\nROUTE A — DEFAULT")
print(f"Distance: {distance_default:,.2f} NM")
print("Passages:", route_default.properties.get("passages"))

print("\nROUTE B — AVOID SUEZ")
print(f"Distance: {distance_avoid_suez:,.2f} NM")
print("Passages:", route_avoid_suez.properties.get("passages"))

print("\nDISTANCE DIFFERENCE")
print(f"{distance_avoid_suez - distance_default:,.2f} NM")

VOYAGE PLANNER — PASSAGE COMPARISON
-----------------------------------

ROUTE A — DEFAULT
Distance: 8,368.16 NM
Passages: None

ROUTE B — AVOID SUEZ
Distance: 10,426.01 NM
Passages: None

DISTANCE DIFFERENCE
2,057.86 NM

In [38]:
import folium
from IPython.display import display

# Create comparison map
comparison_map = folium.Map(
    location=[10, 40],
    zoom_start=2,
    tiles="OpenStreetMap"
)

# Convert default route coordinates
default_coordinates = [
    [lat, lon]
    for lon, lat in route_default.geometry["coordinates"]
]

# Convert Suez-restricted route coordinates
avoid_suez_coordinates = [
    [lat, lon]
    for lon, lat in route_avoid_suez.geometry["coordinates"]
]

# Draw default route
folium.PolyLine(
    locations=default_coordinates,
    color="blue",
    weight=4,
    opacity=0.85,
    tooltip=f"Default Route: {distance_default:,.2f} NM"
).add_to(comparison_map)

# Draw alternative route
folium.PolyLine(
    locations=avoid_suez_coordinates,
    color="red",
    weight=4,
    opacity=0.85,
    tooltip=f"Avoid Suez: {distance_avoid_suez:,.2f} NM"
).add_to(comparison_map)

# Add Singapore marker
folium.Marker(
    location=[1.2644, 103.82],
    popup="Singapore — Origin",
    icon=folium.Icon(color="green", icon="play")
).add_to(comparison_map)

# Add Rotterdam marker
folium.Marker(
    location=[51.95, 4.14],
    popup="Rotterdam — Destination",
    icon=folium.Icon(color="purple", icon="flag")
).add_to(comparison_map)

# Add route legend
legend_html = """
<div style="
    position: fixed;
    bottom: 40px;
    left: 40px;
    width: 200px;
    background-color: white;
    border: 2px solid grey;
    z-index: 9999;
    padding: 10px;
    font-size: 13px;
    color: black;
">
<b>Route Comparison</b><br>
<span style="color:blue;">━━━</span> Default Route<br>
<span style="color:red;">━━━</span> Avoid Suez
</div>
"""

comparison_map.get_root().html.add_child(
    folium.Element(legend_html)
)

# Fit map to both routes
comparison_map.fit_bounds(
    default_coordinates + avoid_suez_coordinates
)

# Display map
display(comparison_map)

In [40]:
import ipywidgets as widgets
from IPython.display import display

# Define supported passage restrictions
passage_options = [
    ("Automatic — Default Route", []),
    ("Avoid Suez Canal", ["suez"]),
    ("Avoid Panama Canal", ["panama"]),
    ("Avoid Suez and Panama Canals", ["suez", "panama"])
]

# Create passage restriction dropdown
restriction_dropdown = widgets.Dropdown(
    options=passage_options,
    description="Passage Restrictions:",
    style={"description_width": "initial"},
    layout=widgets.Layout(width="450px")
)

display(
    widgets.HTML("<h3>Maritime Passage Restrictions</h3>"),
    restriction_dropdown
)

HTML(value='<h3>Maritime Passage Restrictions</h3>')

Dropdown(description='Passage Restrictions:', layout=Layout(width='450px'), options=(('Automatic — Default Rou…

In [42]:
# Retrieve selected passage restrictions
selected_restrictions = restriction_dropdown.value

print("VOYAGE PLANNER — PASSAGE RESTRICTIONS")
print("------------------------------------")

if selected_restrictions:
    print("Selected restrictions:", selected_restrictions)
else:
    print("Selected restrictions: None (Automatic)")

VOYAGE PLANNER — PASSAGE RESTRICTIONS
------------------------------------
Selected restrictions: None (Automatic)

In [44]:
import ipywidgets as widgets
import folium
import searoute as sr

from IPython.display import display, clear_output

# Create new calculation button
restricted_route_button = widgets.Button(
    description="Calculate Route",
    button_style="primary",
    icon="ship",
    layout=widgets.Layout(width="200px")
)

# Create output area
restricted_route_output = widgets.Output()


def calculate_restricted_route(button):

    with restricted_route_output:
        clear_output(wait=True)

        try:
            # Retrieve user selections
            origin_id = origin_dropdown.value
            destination_id = destination_dropdown.value
            vessel_speed = speed_input.value
            selected_restrictions = restriction_dropdown.value

            # Validate inputs
            if origin_id == destination_id:
                print("Error: Origin and destination cannot be the same.")
                return

            if vessel_speed <= 0:
                print("Error: Vessel speed must be greater than zero.")
                return

            # Retrieve port information
            origin = active_ports[
                active_ports["port_id"] == origin_id
            ].iloc[0]

            destination = active_ports[
                active_ports["port_id"] == destination_id
            ].iloc[0]

            # Convert coordinates to searoute format
            origin_coords = [
                float(origin["approach_longitude"]),
                float(origin["approach_latitude"])
            ]

            destination_coords = [
                float(destination["approach_longitude"]),
                float(destination["approach_latitude"])
            ]

            # Calculate route with selected restrictions
            route = sr.searoute(
                origin_coords,
                destination_coords,
                units="naut",
                restrictions=selected_restrictions
            )

            # Extract route information
            route_distance = route.properties["length"]
            route_coordinates = route.geometry["coordinates"]

            # Calculate estimated sailing duration
            voyage_hours = route_distance / vessel_speed
            voyage_days = voyage_hours / 24

            # Display voyage summary
            print("VOYAGE PLANNER — ROUTE SUMMARY")
            print("--------------------------------")
            print(f"Origin: {origin['port_name']}")
            print(f"Destination: {destination['port_name']}")

            if selected_restrictions:
                print(
                    "Passage restrictions:",
                    ", ".join(selected_restrictions)
                )
            else:
                print("Passage restrictions: None")

            print(f"Maritime distance: {route_distance:,.2f} NM")
            print(f"Vessel speed: {vessel_speed:.1f} knots")
            print(f"Estimated sailing time: {voyage_hours:.2f} hours")
            print(f"Estimated sailing duration: {voyage_days:.2f} days")

            # Convert coordinates for Folium
            folium_coordinates = [
                [lat, lon]
                for lon, lat in route_coordinates
            ]

            # Create interactive map
            route_map = folium.Map(
                location=folium_coordinates[0],
                zoom_start=3,
                tiles="OpenStreetMap"
            )

            # Draw maritime route
            folium.PolyLine(
                locations=folium_coordinates,
                color="blue",
                weight=4,
                opacity=0.85,
                tooltip=f"{route_distance:,.2f} NM"
            ).add_to(route_map)

            # Add origin marker
            folium.Marker(
                location=[origin_coords[1], origin_coords[0]],
                popup=f"Origin: {origin['port_name']}",
                tooltip=f"Origin: {origin['port_name']}",
                icon=folium.Icon(
                    color="green",
                    icon="play"
                )
            ).add_to(route_map)

            # Add destination marker
            folium.Marker(
                location=[destination_coords[1], destination_coords[0]],
                popup=f"Destination: {destination['port_name']}",
                tooltip=f"Destination: {destination['port_name']}",
                icon=folium.Icon(
                    color="red",
                    icon="flag"
                )
            ).add_to(route_map)

            # Fit map to route
            route_map.fit_bounds(folium_coordinates)

            # Display map
            display(route_map)

        except Exception as error:
            print("Route calculation failed.")
            print("Error details:", error)


# Connect button
restricted_route_button.on_click(calculate_restricted_route)

# Display updated interface
display(
    widgets.HTML("<h2>Maritime Voyage Planner — Passage Controls</h2>"),
    origin_dropdown,
    destination_dropdown,
    speed_input,
    restriction_dropdown,
    restricted_route_button,
    restricted_route_output
)

HTML(value='<h2>Maritime Voyage Planner — Passage Controls</h2>')

Dropdown(description='Origin:', layout=Layout(width='400px'), options=(('Algeciras (Spain)', 'ESALG'), ('Antwe…

Dropdown(description='Destination:', layout=Layout(width='400px'), options=(('Algeciras (Spain)', 'ESALG'), ('…

BoundedFloatText(value=15.0, description='Vessel Speed (knots):', layout=Layout(width='300px'), max=40.0, min=…

Dropdown(description='Passage Restrictions:', layout=Layout(width='450px'), options=(('Automatic — Default Rou…

Button(button_style='primary', description='Calculate Route', icon='ship', layout=Layout(width='200px'), style…

Output()

In [46]:
import searoute as sr

# Singapore and Rotterdam coordinates
singapore = [103.82, 1.2644]
rotterdam = [4.14, 51.95]

# Compare available routing restrictions
restriction_tests = {
    "Default": [],
    "Avoid Suez": ["suez"],
    "Avoid Suez and Panama": ["suez", "panama"],
    "Avoid Suez, Panama and Northwest": [
        "suez",
        "panama",
        "northwest"
    ]
}

print("VOYAGE PLANNER — ROUTING RESTRICTION TEST")
print("-----------------------------------------")

for name, restrictions in restriction_tests.items():

    try:
        route = sr.searoute(
            singapore,
            rotterdam,
            units="naut",
            restrictions=restrictions
        )

        distance = route.properties["length"]

        print(f"\n{name}")
        print(f"Restrictions: {restrictions}")
        print(f"Distance: {distance:,.2f} NM")

    except Exception as error:
        print(f"\n{name}")
        print("Error:", error)

VOYAGE PLANNER — ROUTING RESTRICTION TEST
-----------------------------------------

Default
Restrictions: []
Distance: 8,368.16 NM

Avoid Suez
Restrictions: ['suez']
Distance: 10,426.01 NM

Avoid Suez and Panama
Restrictions: ['suez', 'panama']
Distance: 10,426.01 NM

Avoid Suez, Panama and Northwest
Restrictions: ['suez', 'panama', 'northwest']
Distance: 11,856.33 NM

In [48]:
import searoute as sr
import folium
from IPython.display import display

# Singapore and Rotterdam coordinates
singapore = [103.82, 1.2644]
rotterdam = [4.14, 51.95]

# Calculate route with all three restrictions
route_no_arctic = sr.searoute(
    singapore,
    rotterdam,
    units="naut",
    restrictions=["suez", "panama", "northwest"]
)

# Extract route information
distance_no_arctic = route_no_arctic.properties["length"]

route_coordinates = [
    [lat, lon]
    for lon, lat in route_no_arctic.geometry["coordinates"]
]

# Create map
test_map = folium.Map(
    location=[10, 40],
    zoom_start=2,
    tiles="OpenStreetMap"
)

# Draw route
folium.PolyLine(
    locations=route_coordinates,
    color="purple",
    weight=4,
    opacity=0.85,
    tooltip=f"Distance: {distance_no_arctic:,.2f} NM"
).add_to(test_map)

# Add origin marker
folium.Marker(
    location=[1.2644, 103.82],
    popup="Singapore",
    icon=folium.Icon(color="green")
).add_to(test_map)

# Add destination marker
folium.Marker(
    location=[51.95, 4.14],
    popup="Rotterdam",
    icon=folium.Icon(color="red")
).add_to(test_map)

# Fit map to route
test_map.fit_bounds(route_coordinates)

# Display results
print("VOYAGE PLANNER — ROUTE VERIFICATION")
print("-----------------------------------")
print("Restrictions: Suez, Panama, Northwest")
print(f"Distance: {distance_no_arctic:,.2f} NM")

display(test_map)

VOYAGE PLANNER — ROUTE VERIFICATION
-----------------------------------
Restrictions: Suez, Panama, Northwest
Distance: 11,856.33 NM

In [50]:
# Update passage restriction options
passage_options = [
    ("Automatic — Default Route", []),
    ("Avoid Suez Canal", ["suez"]),
    ("Avoid Panama Canal", ["panama"]),
    ("Avoid Suez and Panama Canals", ["suez", "panama"]),
    (
        "Avoid Suez, Panama and Northwest Passage",
        ["suez", "panama", "northwest"]
    )
]

# Update existing dropdown
restriction_dropdown.options = passage_options

# Display updated dropdown
display(restriction_dropdown)

Dropdown(description='Passage Restrictions:', layout=Layout(width='450px'), options=(('Automatic — Default Rou…

In [52]:
# ============================================================
# MARITIME VOYAGE PLANNER
# Project 6: Maritime Distance and Voyage Calculation Service
#
# Consolidated Jupyter Notebook Prototype
#
# Features:
# 1. Port-to-Port Voyage Planning
# 2. Multi-Leg Voyage Planning
# 3. Maritime Distance Calculation
# 4. Estimated Sailing Duration
# 5. Passage Restrictions
# 6. Alternative Route Comparison
# 7. Interactive Maritime Maps
# 8. Input Validation
#
# Routing Engine: searoute (prototype)
# UI Framework: ipywidgets
# Map Framework: Folium
# ============================================================


# ============================================================
# 1. IMPORT LIBRARIES
# ============================================================

import pandas as pd
import folium
import searoute as sr
import ipywidgets as widgets

from pathlib import Path
from IPython.display import display, clear_output


# ============================================================
# 2. LOAD PORT DATASET
# ============================================================

DATASET_PATH = Path("voyage_planner_datasets_20261006.xlsx")

if not DATASET_PATH.exists():
    raise FileNotFoundError(
        f"Dataset not found: {DATASET_PATH.resolve()}"
    )

ports_df = pd.read_excel(
    DATASET_PATH,
    sheet_name="Port Reference"
)

active_ports = ports_df[
    ports_df["status"].astype(str).str.lower() == "active"
].copy()

active_ports = active_ports[
    [
        "port_id",
        "port_name",
        "country",
        "latitude",
        "longitude",
        "approach_latitude",
        "approach_longitude"
    ]
]

active_ports = active_ports.sort_values(
    "port_name"
).reset_index(drop=True)

port_lookup = active_ports.set_index("port_id")

port_options = [
    (
        f"{row['port_name']} ({row['country']})",
        row["port_id"]
    )
    for _, row in active_ports.iterrows()
]

print(f"Successfully loaded {len(active_ports)} active ports.")


# ============================================================
# 3. PASSAGE RESTRICTIONS
# ============================================================

PASSAGE_OPTIONS = [
    ("Automatic — Default Route", []),
    ("Avoid Suez Canal", ["suez"]),
    ("Avoid Panama Canal", ["panama"]),
    (
        "Avoid Suez and Panama Canals",
        ["suez", "panama"]
    ),
    (
        "Avoid Suez, Panama and Northwest Passage",
        ["suez", "panama", "northwest"]
    )
]


# ============================================================
# 4. HELPER FUNCTIONS
# ============================================================

def get_port(port_id):
    """Retrieve port information from the dataset."""

    if port_id not in port_lookup.index:
        raise ValueError(f"Unknown port ID: {port_id}")

    return port_lookup.loc[port_id]


def get_coordinates(port_id):
    """Return coordinates in searoute format [lon, lat]."""

    port = get_port(port_id)

    return [
        float(port["approach_longitude"]),
        float(port["approach_latitude"])
    ]


def calculate_route(origin_id, destination_id, restrictions=None):
    """Calculate a maritime route using searoute."""

    if origin_id == destination_id:
        raise ValueError(
            "Origin and destination cannot be the same."
        )

    if restrictions is None:
        restrictions = []

    origin_coords = get_coordinates(origin_id)
    destination_coords = get_coordinates(destination_id)

    route = sr.searoute(
        origin_coords,
        destination_coords,
        units="naut",
        restrictions=restrictions
    )

    distance = float(route.properties["length"])
    coordinates = route.geometry["coordinates"]

    if not coordinates or distance <= 0:
        raise ValueError("No valid maritime route was returned.")

    return {
        "origin_id": origin_id,
        "destination_id": destination_id,
        "origin": get_port(origin_id)["port_name"],
        "destination": get_port(destination_id)["port_name"],
        "distance_nm": distance,
        "coordinates": coordinates,
        "restrictions": list(restrictions)
    }


def calculate_duration(distance_nm, speed_knots):
    """Calculate estimated sailing time."""

    if speed_knots <= 0:
        raise ValueError(
            "Vessel speed must be greater than zero."
        )

    hours = distance_nm / speed_knots
    days = hours / 24

    return {
        "hours": hours,
        "days": days
    }


def create_map(routes, port_ids):
    """Create an interactive Folium map."""

    voyage_map = folium.Map(
        location=[20, 40],
        zoom_start=2,
        tiles="OpenStreetMap"
    )

    colors = [
        "blue",
        "green",
        "purple",
        "orange",
        "red",
        "darkblue"
    ]

    all_coordinates = []

    for index, route in enumerate(routes):

        coordinates = [
            [lat, lon]
            for lon, lat in route["coordinates"]
        ]

        all_coordinates.extend(coordinates)

        color = colors[index % len(colors)]

        folium.PolyLine(
            locations=coordinates,
            color=color,
            weight=4,
            opacity=0.85,
            tooltip=(
                f"{route['origin']} → "
                f"{route['destination']}: "
                f"{route['distance_nm']:,.2f} NM"
            )
        ).add_to(voyage_map)

    for index, port_id in enumerate(port_ids):

        port = get_port(port_id)

        coordinates = [
            float(port["approach_latitude"]),
            float(port["approach_longitude"])
        ]

        if index == 0:
            marker_color = "green"
        elif index == len(port_ids) - 1:
            marker_color = "red"
        else:
            marker_color = "blue"

        folium.Marker(
            location=coordinates,
            popup=(
                f"Stop {index + 1}: "
                f"{port['port_name']}"
            ),
            tooltip=port["port_name"],
            icon=folium.Icon(
                color=marker_color,
                icon="info-sign"
            )
        ).add_to(voyage_map)

    if all_coordinates:
        voyage_map.fit_bounds(all_coordinates)

    return voyage_map


# ============================================================
# 5. SHARED APPLICATION STATE
# ============================================================

latest_result = None
voyage_stops = []


# ============================================================
# 6. SHARED UI COMPONENTS
# ============================================================

speed_input = widgets.BoundedFloatText(
    value=15.0,
    min=1.0,
    max=40.0,
    step=0.5,
    description="Vessel Speed (knots):",
    style={"description_width": "initial"},
    layout=widgets.Layout(width="350px")
)

restriction_dropdown = widgets.Dropdown(
    options=PASSAGE_OPTIONS,
    description="Passage Restrictions:",
    style={"description_width": "initial"},
    layout=widgets.Layout(width="500px")
)


# ============================================================
# 7. PORT-TO-PORT VOYAGE PLANNER
# ============================================================

origin_dropdown = widgets.Dropdown(
    options=port_options,
    description="Origin:",
    style={"description_width": "initial"},
    layout=widgets.Layout(width="400px")
)

destination_dropdown = widgets.Dropdown(
    options=port_options,
    description="Destination:",
    style={"description_width": "initial"},
    layout=widgets.Layout(width="400px")
)

port_route_button = widgets.Button(
    description="Calculate Route",
    button_style="primary",
    icon="ship"
)

port_output = widgets.Output()


def calculate_port_route_clicked(button):

    global latest_result

    with port_output:

        clear_output(wait=True)

        latest_result = None

        try:
            origin_id = origin_dropdown.value
            destination_id = destination_dropdown.value

            speed = float(speed_input.value)
            restrictions = list(restriction_dropdown.value)

            route = calculate_route(
                origin_id,
                destination_id,
                restrictions
            )

            duration = calculate_duration(
                route["distance_nm"],
                speed
            )

            latest_result = {
                "voyage_type": "port_to_port",
                "ports": [origin_id, destination_id],
                "speed_knots": speed,
                "restrictions": restrictions,
                "total_distance_nm": route["distance_nm"],
                "duration_hours": duration["hours"],
                "duration_days": duration["days"],
                "legs": [
                    {
                        "leg_number": 1,
                        **route
                    }
                ]
            }

            print("PORT-TO-PORT VOYAGE SUMMARY")
            print("----------------------------")

            print(f"Origin: {route['origin']}")
            print(f"Destination: {route['destination']}")

            print(
                "Restrictions:",
                ", ".join(restrictions) or "None"
            )

            print(
                f"Maritime Distance: "
                f"{route['distance_nm']:,.2f} NM"
            )

            print(f"Vessel Speed: {speed:.1f} knots")

            print(
                f"Estimated Sailing Time: "
                f"{duration['hours']:.2f} hours"
            )

            print(
                f"Estimated Sailing Duration: "
                f"{duration['days']:.2f} days"
            )

            voyage_map = create_map(
                [route],
                [origin_id, destination_id]
            )

            display(voyage_map)

        except Exception as error:
            print("Route calculation failed.")
            print("Error:", error)


port_route_button.on_click(calculate_port_route_clicked)


# ============================================================
# 8. MULTI-LEG VOYAGE PLANNER
# ============================================================

stop_dropdown = widgets.Dropdown(
    options=port_options,
    description="Select Port:",
    style={"description_width": "initial"},
    layout=widgets.Layout(width="400px")
)

add_stop_button = widgets.Button(
    description="Add Stop",
    button_style="success",
    icon="plus"
)

remove_stop_button = widgets.Button(
    description="Remove Last Stop",
    button_style="warning",
    icon="minus"
)

clear_stops_button = widgets.Button(
    description="Clear All",
    button_style="danger",
    icon="trash"
)

calculate_multi_button = widgets.Button(
    description="Calculate Multi-Leg Voyage",
    button_style="primary",
    icon="ship"
)

itinerary_output = widgets.Output()
multi_output = widgets.Output()


def display_itinerary():

    with itinerary_output:

        clear_output(wait=True)

        print("VOYAGE ITINERARY")
        print("----------------")

        if not voyage_stops:
            print("No ports selected.")
            return

        for index, port_id in enumerate(voyage_stops, 1):

            port = get_port(port_id)

            print(f"{index}. {port['port_name']}")


def add_stop_clicked(button):

    global latest_result

    selected_port = stop_dropdown.value

    if voyage_stops and voyage_stops[-1] == selected_port:

        with itinerary_output:
            clear_output(wait=True)
            print(
                "Error: Consecutive stops "
                "cannot be the same port."
            )

        return

    voyage_stops.append(selected_port)
    latest_result = None

    display_itinerary()


def remove_stop_clicked(button):

    global latest_result

    if voyage_stops:
        voyage_stops.pop()

    latest_result = None
    display_itinerary()


def clear_stops_clicked(button):

    global latest_result

    voyage_stops.clear()
    latest_result = None

    display_itinerary()


add_stop_button.on_click(add_stop_clicked)
remove_stop_button.on_click(remove_stop_clicked)
clear_stops_button.on_click(clear_stops_clicked)


def calculate_multi_clicked(button):

    global latest_result

    with multi_output:

        clear_output(wait=True)
        latest_result = None

        try:
            if len(voyage_stops) < 2:
                raise ValueError(
                    "Please add at least two ports."
                )

            speed = float(speed_input.value)
            restrictions = list(restriction_dropdown.value)

            routes = []

            for index in range(len(voyage_stops) - 1):

                route = calculate_route(
                    voyage_stops[index],
                    voyage_stops[index + 1],
                    restrictions
                )

                route["leg_number"] = index + 1

                routes.append(route)

            total_distance = sum(
                route["distance_nm"]
                for route in routes
            )

            duration = calculate_duration(
                total_distance,
                speed
            )

            latest_result = {
                "voyage_type": "multi_leg",
                "ports": list(voyage_stops),
                "speed_knots": speed,
                "restrictions": restrictions,
                "total_distance_nm": total_distance,
                "duration_hours": duration["hours"],
                "duration_days": duration["days"],
                "legs": routes
            }

            print("MULTI-LEG VOYAGE SUMMARY")
            print("-------------------------")

            results_df = pd.DataFrame([
                {
                    "Leg": route["leg_number"],
                    "Origin": route["origin"],
                    "Destination": route["destination"],
                    "Distance (NM)": round(
                        route["distance_nm"], 2
                    )
                }
                for route in routes
            ])

            display(results_df)

            print(
                f"\nTotal Distance: "
                f"{total_distance:,.2f} NM"
            )

            print(f"Vessel Speed: {speed:.1f} knots")

            print(
                "Restrictions:",
                ", ".join(restrictions) or "None"
            )

            print(
                f"Estimated Sailing Time: "
                f"{duration['hours']:.2f} hours"
            )

            print(
                f"Estimated Sailing Duration: "
                f"{duration['days']:.2f} days"
            )

            voyage_map = create_map(
                routes,
                voyage_stops
            )

            display(voyage_map)

        except Exception as error:
            print("Multi-leg calculation failed.")
            print("Error:", error)


calculate_multi_button.on_click(calculate_multi_clicked)


# ============================================================
# 9. ROUTE COMPARISON
# ============================================================

compare_button = widgets.Button(
    description="Compare Routes",
    button_style="info",
    icon="exchange"
)

comparison_output = widgets.Output()


def compare_routes_clicked(button):

    with comparison_output:

        clear_output(wait=True)

        try:
            origin_id = origin_dropdown.value
            destination_id = destination_dropdown.value

            if origin_id == destination_id:
                raise ValueError(
                    "Select two different ports."
                )

            selected_restrictions = list(
                restriction_dropdown.value
            )

            default_route = calculate_route(
                origin_id,
                destination_id,
                []
            )

            restricted_route = calculate_route(
                origin_id,
                destination_id,
                selected_restrictions
            )

            difference = (
                restricted_route["distance_nm"]
                - default_route["distance_nm"]
            )

            print("ROUTE COMPARISON")
            print("----------------")

            print(
                f"Default Route: "
                f"{default_route['distance_nm']:,.2f} NM"
            )

            print(
                f"Restricted Route: "
                f"{restricted_route['distance_nm']:,.2f} NM"
            )

            print(
                f"Distance Difference: "
                f"{difference:,.2f} NM"
            )

            comparison_map = folium.Map(
                location=[20, 40],
                zoom_start=2,
                tiles="OpenStreetMap"
            )

            all_coordinates = []

            for route, color, label in [
                (default_route, "blue", "Default"),
                (restricted_route, "red", "Restricted")
            ]:

                coordinates = [
                    [lat, lon]
                    for lon, lat in route["coordinates"]
                ]

                all_coordinates.extend(coordinates)

                folium.PolyLine(
                    locations=coordinates,
                    color=color,
                    weight=4,
                    opacity=0.85,
                    tooltip=(
                        f"{label}: "
                        f"{route['distance_nm']:,.2f} NM"
                    )
                ).add_to(comparison_map)

            for port_id, color in [
                (origin_id, "green"),
                (destination_id, "purple")
            ]:

                port = get_port(port_id)

                folium.Marker(
                    location=[
                        float(port["approach_latitude"]),
                        float(port["approach_longitude"])
                    ],
                    popup=port["port_name"],
                    icon=folium.Icon(color=color)
                ).add_to(comparison_map)

            comparison_map.fit_bounds(all_coordinates)

            legend_html = """
            <div style="
                position: fixed;
                bottom: 40px;
                left: 40px;
                width: 190px;
                background-color: white;
                border: 2px solid grey;
                z-index: 9999;
                padding: 10px;
                color: black;
                font-size: 13px;
            ">
                <b>Route Comparison</b><br>
                <span style="color:blue;">━━━</span>
                Default Route<br>
                <span style="color:red;">━━━</span>
                Restricted Route
            </div>
            """

            comparison_map.get_root().html.add_child(
                folium.Element(legend_html)
            )

            display(comparison_map)

        except Exception as error:
            print("Route comparison failed.")
            print("Error:", error)


compare_button.on_click(compare_routes_clicked)


# ============================================================
# 10. BUILD APPLICATION INTERFACE
# ============================================================

port_to_port_tab = widgets.VBox([
    widgets.HTML("<h3>Port-to-Port Voyage Planning</h3>"),
    origin_dropdown,
    destination_dropdown,
    port_route_button,
    port_output
])

multi_leg_tab = widgets.VBox([
    widgets.HTML("<h3>Multi-Leg Voyage Planning</h3>"),
    stop_dropdown,
    widgets.HBox([
        add_stop_button,
        remove_stop_button,
        clear_stops_button
    ]),
    itinerary_output,
    calculate_multi_button,
    multi_output
])

comparison_tab = widgets.VBox([
    widgets.HTML("<h3>Alternative Route Comparison</h3>"),
    widgets.HTML(
        "<p>Uses the origin and destination selected "
        "in the Port-to-Port tab and the shared "
        "passage restrictions.</p>"
    ),
    compare_button,
    comparison_output
])

tabs = widgets.Tab(
    children=[
        port_to_port_tab,
        multi_leg_tab,
        comparison_tab
    ]
)

tabs.set_title(0, "Port-to-Port")
tabs.set_title(1, "Multi-Leg")
tabs.set_title(2, "Route Comparison")


# ============================================================
# 11. DISPLAY APPLICATION
# ============================================================

display(
    widgets.HTML(
        """
        <h1>Maritime Voyage Planner</h1>
        <p>
        Project 6 — Maritime Distance and
        Voyage Calculation Service
        </p>
        <p>
        <b>Prototype:</b> Routes generated using
        the open-source searoute library.
        Distances and routes require validation
        before operational use.
        </p>
        """
    ),

    widgets.HTML("<h3>Voyage Settings</h3>"),

    speed_input,

    restriction_dropdown,

    widgets.HTML("<hr>"),

    tabs
)

display_itinerary()

print("\nMaritime Voyage Planner initialized successfully.")

Successfully loaded 29 active ports.

HTML(value='\n        <h1>Maritime Voyage Planner</h1>\n        <p>\n        Project 6 — Maritime Distance and…

HTML(value='<h3>Voyage Settings</h3>')

BoundedFloatText(value=15.0, description='Vessel Speed (knots):', layout=Layout(width='350px'), max=40.0, min=…

Dropdown(description='Passage Restrictions:', layout=Layout(width='500px'), options=(('Automatic — Default Rou…

HTML(value='<hr>')

Tab(children=(VBox(children=(HTML(value='<h3>Port-to-Port Voyage Planning</h3>'), Dropdown(description='Origin…

Maritime Voyage Planner initialized successfully.

In [54]:
# ============================================================
# TEST: MULTI-LEG ROUTE COMPARISON
# ============================================================

multi_compare_button = widgets.Button(
    description="Compare Multi-Leg Routes",
    button_style="info",
    icon="exchange",
    layout=widgets.Layout(width="250px")
)

multi_compare_output = widgets.Output()


def compare_multi_leg_routes(button):

    with multi_compare_output:

        clear_output(wait=True)

        try:
            # --------------------------------------------
            # 1. VALIDATE ITINERARY
            # --------------------------------------------

            if len(voyage_stops) < 2:
                raise ValueError(
                    "Please add at least two ports in the Multi-Leg tab."
                )

            speed = float(speed_input.value)

            if speed <= 0:
                raise ValueError(
                    "Vessel speed must be greater than zero."
                )

            restrictions = list(restriction_dropdown.value)

            # --------------------------------------------
            # 2. CALCULATE DEFAULT AND RESTRICTED ROUTES
            # --------------------------------------------

            default_routes = []
            restricted_routes = []

            comparison_results = []

            for i in range(len(voyage_stops) - 1):

                origin_id = voyage_stops[i]
                destination_id = voyage_stops[i + 1]

                default_route = calculate_route(
                    origin_id,
                    destination_id,
                    []
                )

                restricted_route = calculate_route(
                    origin_id,
                    destination_id,
                    restrictions
                )

                default_routes.append(default_route)
                restricted_routes.append(restricted_route)

                default_distance = default_route["distance_nm"]
                restricted_distance = restricted_route["distance_nm"]

                comparison_results.append({
                    "Leg": i + 1,
                    "Origin": default_route["origin"],
                    "Destination": default_route["destination"],
                    "Default (NM)": round(default_distance, 2),
                    "Restricted (NM)": round(restricted_distance, 2),
                    "Difference (NM)": round(
                        restricted_distance - default_distance,
                        2
                    )
                })

            # --------------------------------------------
            # 3. CALCULATE TOTAL DISTANCES
            # --------------------------------------------

            total_default = sum(
                route["distance_nm"]
                for route in default_routes
            )

            total_restricted = sum(
                route["distance_nm"]
                for route in restricted_routes
            )

            distance_difference = (
                total_restricted - total_default
            )

            default_hours = total_default / speed
            restricted_hours = total_restricted / speed

            time_difference = (
                restricted_hours - default_hours
            )

            # --------------------------------------------
            # 4. DISPLAY COMPARISON TABLE
            # --------------------------------------------

            print("MULTI-LEG ROUTE COMPARISON")
            print("=" * 60)

            comparison_df = pd.DataFrame(comparison_results)

            display(comparison_df)

            print("\nTOTAL VOYAGE COMPARISON")
            print("-" * 60)

            summary_df = pd.DataFrame({
                "Metric": [
                    "Total Distance (NM)",
                    "Sailing Time (Hours)",
                    "Sailing Duration (Days)"
                ],
                "Default Route": [
                    round(total_default, 2),
                    round(default_hours, 2),
                    round(default_hours / 24, 2)
                ],
                "Restricted Route": [
                    round(total_restricted, 2),
                    round(restricted_hours, 2),
                    round(restricted_hours / 24, 2)
                ]
            })

            summary_df["Difference"] = (
                summary_df["Restricted Route"]
                - summary_df["Default Route"]
            ).round(2)

            display(summary_df)

            print(f"\nVessel Speed: {speed:.1f} knots")

            print(
                "Passage Restrictions:",
                ", ".join(restrictions) or "None"
            )

            print(
                f"Total Distance Difference: "
                f"{distance_difference:+,.2f} NM"
            )

            print(
                f"Additional Sailing Time: "
                f"{time_difference:+,.2f} hours"
            )

            # --------------------------------------------
            # 5. CREATE COMPARISON MAP
            # --------------------------------------------

            comparison_map = folium.Map(
                location=[20, 40],
                zoom_start=2,
                tiles="OpenStreetMap"
            )

            all_coordinates = []

            # Default routes: BLUE
            for i, route in enumerate(default_routes):

                coordinates = [
                    [lat, lon]
                    for lon, lat in route["coordinates"]
                ]

                all_coordinates.extend(coordinates)

                folium.PolyLine(
                    locations=coordinates,
                    color="blue",
                    weight=4,
                    opacity=0.8,
                    tooltip=(
                        f"Default Leg {i + 1}: "
                        f"{route['origin']} → "
                        f"{route['destination']} "
                        f"({route['distance_nm']:,.2f} NM)"
                    )
                ).add_to(comparison_map)

            # Restricted routes: RED
            for i, route in enumerate(restricted_routes):

                coordinates = [
                    [lat, lon]
                    for lon, lat in route["coordinates"]
                ]

                all_coordinates.extend(coordinates)

                folium.PolyLine(
                    locations=coordinates,
                    color="red",
                    weight=3,
                    opacity=0.8,
                    tooltip=(
                        f"Restricted Leg {i + 1}: "
                        f"{route['origin']} → "
                        f"{route['destination']} "
                        f"({route['distance_nm']:,.2f} NM)"
                    )
                ).add_to(comparison_map)

            # --------------------------------------------
            # 6. ADD PORT MARKERS
            # --------------------------------------------

            for i, port_id in enumerate(voyage_stops):

                port = get_port(port_id)

                if i == 0:
                    marker_color = "green"
                elif i == len(voyage_stops) - 1:
                    marker_color = "purple"
                else:
                    marker_color = "blue"

                folium.Marker(
                    location=[
                        float(port["approach_latitude"]),
                        float(port["approach_longitude"])
                    ],
                    popup=(
                        f"Stop {i + 1}: "
                        f"{port['port_name']}"
                    ),
                    tooltip=port["port_name"],
                    icon=folium.Icon(
                        color=marker_color,
                        icon="info-sign"
                    )
                ).add_to(comparison_map)

            # --------------------------------------------
            # 7. ADD MAP LEGEND
            # --------------------------------------------

            legend_html = """
            <div style="
                position: fixed;
                bottom: 40px;
                left: 40px;
                width: 220px;
                background-color: white;
                border: 2px solid grey;
                z-index: 9999;
                padding: 10px;
                color: black;
                font-size: 13px;
            ">
                <b>Multi-Leg Route Comparison</b><br><br>
                <span style="color:blue;">━━━━</span>
                Default Route<br>
                <span style="color:red;">┄┄┄┄</span>
                Restricted Route<br><br>
                🟢 Origin<br>
                🔵 Intermediate Port<br>
                🟣 Final Destination
            </div>
            """

            comparison_map.get_root().html.add_child(
                folium.Element(legend_html)
            )

            # --------------------------------------------
            # 8. FIT MAP TO ROUTES
            # --------------------------------------------

            if all_coordinates:
                comparison_map.fit_bounds(all_coordinates)

            display(comparison_map)

        except Exception as error:

            print("Multi-leg route comparison failed.")
            print("Error:", error)


multi_compare_button.on_click(compare_multi_leg_routes)

display(
    widgets.HTML("<h3>Multi-Leg Route Comparison Test</h3>"),
    widgets.HTML(
        "<p>Compares the itinerary from your existing "
        "Multi-Leg tab using default and restricted routing.</p>"
    ),
    multi_compare_button,
    multi_compare_output
)

HTML(value='<h3>Multi-Leg Route Comparison Test</h3>')

HTML(value='<p>Compares the itinerary from your existing Multi-Leg tab using default and restricted routing.</…

Button(button_style='info', description='Compare Multi-Leg Routes', icon='exchange', layout=Layout(width='250p…

Output()

In [56]:
# ============================================================
# MARITIME VOYAGE PLANNER
# Project 6: Maritime Distance and Voyage Calculation Service
#
# Consolidated Jupyter Notebook Prototype
#
# Features:
# 1. Port-to-Port Voyage Planning and Comparison
# 2. Multi-Leg Voyage Planning and Comparison
# 3. Maritime Distance Calculation
# 4. Estimated Sailing Duration
# 5. Passage Restrictions
# 6. Interactive Maritime Maps
# 7. Input Validation
#
# Routing Engine: searoute (prototype)
# UI Framework: ipywidgets
# Map Framework: Folium
# ============================================================


# ============================================================
# 1. IMPORT LIBRARIES
# ============================================================

import pandas as pd
import folium
import searoute as sr
import ipywidgets as widgets

from pathlib import Path
from IPython.display import display, clear_output


# ============================================================
# 2. LOAD PORT DATASET
# ============================================================

DATASET_PATH = Path("voyage_planner_datasets_20261006.xlsx")

if not DATASET_PATH.exists():
    raise FileNotFoundError(
        f"Dataset not found: {DATASET_PATH.resolve()}"
    )

ports_df = pd.read_excel(
    DATASET_PATH,
    sheet_name="Port Reference"
)

active_ports = ports_df[
    ports_df["status"].astype(str).str.strip().str.lower() == "active"
].copy()

active_ports = active_ports[
    [
        "port_id",
        "port_name",
        "country",
        "latitude",
        "longitude",
        "approach_latitude",
        "approach_longitude"
    ]
]

active_ports = active_ports.sort_values(
    "port_name"
).reset_index(drop=True)

if active_ports.empty:
    raise ValueError("No active ports found in the dataset.")

port_lookup = active_ports.set_index("port_id")

port_options = [
    (
        f"{row['port_name']} ({row['country']})",
        row["port_id"]
    )
    for _, row in active_ports.iterrows()
]

print(f"Successfully loaded {len(active_ports)} active ports.")


# ============================================================
# 3. PASSAGE RESTRICTIONS
# ============================================================

PASSAGE_OPTIONS = [
    ("Automatic — No Restrictions", []),
    ("Avoid Suez Canal", ["suez"]),
    ("Avoid Panama Canal", ["panama"]),
    (
        "Avoid Suez and Panama Canals",
        ["suez", "panama"]
    ),
    (
        "Avoid Suez, Panama and Northwest Passage",
        ["suez", "panama", "northwest"]
    )
]


# ============================================================
# 4. HELPER FUNCTIONS
# ============================================================

def get_port(port_id):
    """Retrieve port information."""

    if port_id not in port_lookup.index:
        raise ValueError(f"Unknown port ID: {port_id}")

    return port_lookup.loc[port_id]


def get_coordinates(port_id):
    """Return coordinates in [longitude, latitude] format."""

    port = get_port(port_id)

    longitude = float(port["approach_longitude"])
    latitude = float(port["approach_latitude"])

    if not (-180 <= longitude <= 180):
        raise ValueError("Invalid port longitude.")

    if not (-90 <= latitude <= 90):
        raise ValueError("Invalid port latitude.")

    return [longitude, latitude]


def calculate_route(origin_id, destination_id, restrictions=None):
    """Calculate a maritime route using searoute."""

    if origin_id == destination_id:
        raise ValueError(
            "Origin and destination cannot be the same."
        )

    if restrictions is None:
        restrictions = []

    origin_coords = get_coordinates(origin_id)
    destination_coords = get_coordinates(destination_id)

    route = sr.searoute(
        origin_coords,
        destination_coords,
        units="naut",
        restrictions=restrictions
    )

    distance = float(route.properties["length"])
    coordinates = route.geometry["coordinates"]

    if not coordinates or distance <= 0:
        raise ValueError("No valid maritime route was returned.")

    return {
        "origin_id": origin_id,
        "destination_id": destination_id,
        "origin": get_port(origin_id)["port_name"],
        "destination": get_port(destination_id)["port_name"],
        "distance_nm": distance,
        "coordinates": coordinates,
        "restrictions": list(restrictions)
    }


def calculate_duration(distance_nm, speed_knots):
    """Calculate sailing duration."""

    if speed_knots <= 0:
        raise ValueError(
            "Vessel speed must be greater than zero."
        )

    hours = distance_nm / speed_knots

    return {
        "hours": hours,
        "days": hours / 24
    }


def calculate_itinerary_routes(port_ids, restrictions):
    """Calculate every leg in an ordered itinerary."""

    if len(port_ids) < 2:
        raise ValueError("Please select at least two ports.")

    routes = []

    for index in range(len(port_ids) - 1):

        route = calculate_route(
            port_ids[index],
            port_ids[index + 1],
            restrictions
        )

        route["leg_number"] = index + 1
        routes.append(route)

    return routes


def get_total_distance(routes):
    """Calculate the combined distance of all legs."""

    return sum(
        route["distance_nm"]
        for route in routes
    )


# ============================================================
# 5. MAP FUNCTIONS
# ============================================================

def add_port_markers(voyage_map, port_ids):
    """Add origin, intermediate and destination markers."""

    for index, port_id in enumerate(port_ids):

        port = get_port(port_id)

        if index == 0:
            marker_color = "green"

        elif index == len(port_ids) - 1:
            marker_color = "purple"

        else:
            marker_color = "blue"

        folium.Marker(
            location=[
                float(port["approach_latitude"]),
                float(port["approach_longitude"])
            ],
            popup=f"Stop {index + 1}: {port['port_name']}",
            tooltip=port["port_name"],
            icon=folium.Icon(
                color=marker_color,
                icon="info-sign"
            )
        ).add_to(voyage_map)


def create_map(routes, port_ids):
    """Create a standard maritime voyage map."""

    voyage_map = folium.Map(
        location=[20, 40],
        zoom_start=2,
        tiles="OpenStreetMap"
    )

    colors = [
        "blue",
        "green",
        "purple",
        "orange",
        "red",
        "darkblue"
    ]

    all_coordinates = []

    for index, route in enumerate(routes):

        coordinates = [
            [lat, lon]
            for lon, lat in route["coordinates"]
        ]

        all_coordinates.extend(coordinates)

        folium.PolyLine(
            locations=coordinates,
            color=colors[index % len(colors)],
            weight=4,
            opacity=0.85,
            tooltip=(
                f"Leg {index + 1}: "
                f"{route['origin']} → "
                f"{route['destination']} "
                f"({route['distance_nm']:,.2f} NM)"
            )
        ).add_to(voyage_map)

    add_port_markers(voyage_map, port_ids)

    if all_coordinates:
        voyage_map.fit_bounds(all_coordinates)

    return voyage_map


def create_comparison_map(
    default_routes,
    restricted_routes,
    port_ids
):
    """Display unrestricted and restricted routes together."""

    comparison_map = folium.Map(
        location=[20, 40],
        zoom_start=2,
        tiles="OpenStreetMap"
    )

    all_coordinates = []

    route_groups = [
        ("Unrestricted", default_routes, "blue"),
        ("Restricted", restricted_routes, "red")
    ]

    for label, routes, color in route_groups:

        for index, route in enumerate(routes):

            coordinates = [
                [lat, lon]
                for lon, lat in route["coordinates"]
            ]

            all_coordinates.extend(coordinates)

            folium.PolyLine(
                locations=coordinates,
                color=color,
                weight=4,
                opacity=0.85,
                tooltip=(
                    f"{label} Leg {index + 1}: "
                    f"{route['origin']} → "
                    f"{route['destination']} "
                    f"({route['distance_nm']:,.2f} NM)"
                )
            ).add_to(comparison_map)

    add_port_markers(comparison_map, port_ids)

    legend_html = """
    <div style="
        position: fixed;
        bottom: 40px;
        left: 40px;
        width: 220px;
        background-color: white;
        border: 2px solid grey;
        z-index: 9999;
        padding: 10px;
        color: black;
        font-size: 13px;
    ">
        <b>Route Comparison</b><br><br>
        <span style="color:blue;">━━━━</span>
        Unrestricted Route<br>
        <span style="color:red;">━━━━</span>
        Restricted Route<br><br>
        🟢 Origin<br>
        🔵 Intermediate Port<br>
        🟣 Final Destination
    </div>
    """

    comparison_map.get_root().html.add_child(
        folium.Element(legend_html)
    )

    if all_coordinates:
        comparison_map.fit_bounds(all_coordinates)

    return comparison_map


# ============================================================
# 6. SHARED APPLICATION STATE
# ============================================================

voyage_stops = []


# ============================================================
# 7. SHARED VOYAGE SETTINGS
# ============================================================

speed_input = widgets.BoundedFloatText(
    value=15.0,
    min=1.0,
    max=40.0,
    step=0.5,
    description="Vessel Speed (knots):",
    style={"description_width": "initial"},
    layout=widgets.Layout(width="350px")
)

restriction_dropdown = widgets.Dropdown(
    options=PASSAGE_OPTIONS,
    description="Passage Restrictions:",
    style={"description_width": "initial"},
    layout=widgets.Layout(width="500px")
)


# ============================================================
# 8. PORT-TO-PORT VOYAGE PLANNER
# ============================================================

origin_dropdown = widgets.Dropdown(
    options=port_options,
    description="Origin:",
    style={"description_width": "initial"},
    layout=widgets.Layout(width="400px")
)

destination_dropdown = widgets.Dropdown(
    options=port_options,
    description="Destination:",
    style={"description_width": "initial"},
    layout=widgets.Layout(width="400px")
)

port_route_button = widgets.Button(
    description="Calculate Route",
    button_style="primary",
    icon="ship",
    layout=widgets.Layout(width="170px")
)

port_compare_button = widgets.Button(
    description="Compare Routes",
    button_style="info",
    icon="exchange",
    layout=widgets.Layout(width="170px")
)

port_output = widgets.Output()


def calculate_port_route_clicked(button):

    with port_output:

        clear_output(wait=True)

        try:
            origin_id = origin_dropdown.value
            destination_id = destination_dropdown.value

            speed = float(speed_input.value)
            restrictions = list(restriction_dropdown.value)

            route = calculate_route(
                origin_id,
                destination_id,
                restrictions
            )

            duration = calculate_duration(
                route["distance_nm"],
                speed
            )

            print("PORT-TO-PORT VOYAGE SUMMARY")
            print("=" * 55)

            print(f"Origin: {route['origin']}")
            print(f"Destination: {route['destination']}")

            print(
                "Passage Restrictions:",
                ", ".join(restrictions) or "None"
            )

            print(
                f"Maritime Distance: "
                f"{route['distance_nm']:,.2f} NM"
            )

            print(f"Vessel Speed: {speed:.1f} knots")

            print(
                f"Estimated Sailing Time: "
                f"{duration['hours']:.2f} hours"
            )

            print(
                f"Estimated Sailing Duration: "
                f"{duration['days']:.2f} days"
            )

            display(
                create_map(
                    [route],
                    [origin_id, destination_id]
                )
            )

        except Exception as error:
            print("Route calculation failed.")
            print("Error:", error)


def compare_port_routes_clicked(button):

    with port_output:

        clear_output(wait=True)

        try:
            origin_id = origin_dropdown.value
            destination_id = destination_dropdown.value

            speed = float(speed_input.value)
            restrictions = list(restriction_dropdown.value)

            default_route = calculate_route(
                origin_id,
                destination_id,
                []
            )

            restricted_route = calculate_route(
                origin_id,
                destination_id,
                restrictions
            )

            default_distance = default_route["distance_nm"]
            restricted_distance = restricted_route["distance_nm"]

            difference = restricted_distance - default_distance

            default_duration = calculate_duration(
                default_distance,
                speed
            )

            restricted_duration = calculate_duration(
                restricted_distance,
                speed
            )

            print("PORT-TO-PORT ROUTE COMPARISON")
            print("=" * 55)

            print(
                f"Origin: {default_route['origin']}"
            )

            print(
                f"Destination: {default_route['destination']}"
            )

            print(
                "Passage Restrictions:",
                ", ".join(restrictions) or "None"
            )

            comparison_df = pd.DataFrame({
                "Metric": [
                    "Distance (NM)",
                    "Sailing Time (Hours)",
                    "Sailing Duration (Days)"
                ],
                "Unrestricted Route": [
                    round(default_distance, 2),
                    round(default_duration["hours"], 2),
                    round(default_duration["days"], 2)
                ],
                "Restricted Route": [
                    round(restricted_distance, 2),
                    round(restricted_duration["hours"], 2),
                    round(restricted_duration["days"], 2)
                ],
                "Difference": [
                    round(difference, 2),
                    round(
                        restricted_duration["hours"]
                        - default_duration["hours"],
                        2
                    ),
                    round(
                        restricted_duration["days"]
                        - default_duration["days"],
                        2
                    )
                ]
            })

            display(comparison_df)

            display(
                create_comparison_map(
                    [default_route],
                    [restricted_route],
                    [origin_id, destination_id]
                )
            )

        except Exception as error:
            print("Port-to-port comparison failed.")
            print("Error:", error)


port_route_button.on_click(calculate_port_route_clicked)
port_compare_button.on_click(compare_port_routes_clicked)


# ============================================================
# 9. MULTI-LEG VOYAGE PLANNER
# ============================================================

stop_dropdown = widgets.Dropdown(
    options=port_options,
    description="Select Port:",
    style={"description_width": "initial"},
    layout=widgets.Layout(width="400px")
)

add_stop_button = widgets.Button(
    description="Add Stop",
    button_style="success",
    icon="plus"
)

remove_stop_button = widgets.Button(
    description="Remove Last Stop",
    button_style="warning",
    icon="minus"
)

clear_stops_button = widgets.Button(
    description="Clear All",
    button_style="danger",
    icon="trash"
)

calculate_multi_button = widgets.Button(
    description="Calculate Multi-Leg Voyage",
    button_style="primary",
    icon="ship",
    layout=widgets.Layout(width="250px")
)

compare_multi_button = widgets.Button(
    description="Compare Multi-Leg Routes",
    button_style="info",
    icon="exchange",
    layout=widgets.Layout(width="250px")
)

itinerary_output = widgets.Output()
multi_output = widgets.Output()


def display_itinerary():

    with itinerary_output:

        clear_output(wait=True)

        print("VOYAGE ITINERARY")
        print("-" * 35)

        if not voyage_stops:
            print("No ports selected.")
            return

        for index, port_id in enumerate(voyage_stops, 1):

            port = get_port(port_id)

            print(
                f"{index}. {port['port_name']}"
            )


def add_stop_clicked(button):

    selected_port = stop_dropdown.value

    if voyage_stops and voyage_stops[-1] == selected_port:

        with itinerary_output:

            clear_output(wait=True)

            print(
                "Error: Consecutive stops "
                "cannot be the same port."
            )

        return

    voyage_stops.append(selected_port)

    display_itinerary()


def remove_stop_clicked(button):

    if voyage_stops:
        voyage_stops.pop()

    display_itinerary()


def clear_stops_clicked(button):

    voyage_stops.clear()

    display_itinerary()


add_stop_button.on_click(add_stop_clicked)
remove_stop_button.on_click(remove_stop_clicked)
clear_stops_button.on_click(clear_stops_clicked)


def calculate_multi_clicked(button):

    with multi_output:

        clear_output(wait=True)

        try:
            speed = float(speed_input.value)
            restrictions = list(restriction_dropdown.value)

            routes = calculate_itinerary_routes(
                voyage_stops,
                restrictions
            )

            total_distance = get_total_distance(routes)

            duration = calculate_duration(
                total_distance,
                speed
            )

            print("MULTI-LEG VOYAGE SUMMARY")
            print("=" * 60)

            results_df = pd.DataFrame([
                {
                    "Leg": route["leg_number"],
                    "Origin": route["origin"],
                    "Destination": route["destination"],
                    "Distance (NM)": round(
                        route["distance_nm"], 2
                    )
                }
                for route in routes
            ])

            display(results_df)

            print(
                f"\nTotal Distance: "
                f"{total_distance:,.2f} NM"
            )

            print(f"Vessel Speed: {speed:.1f} knots")

            print(
                "Passage Restrictions:",
                ", ".join(restrictions) or "None"
            )

            print(
                f"Estimated Sailing Time: "
                f"{duration['hours']:.2f} hours"
            )

            print(
                f"Estimated Sailing Duration: "
                f"{duration['days']:.2f} days"
            )

            display(
                create_map(
                    routes,
                    voyage_stops
                )
            )

        except Exception as error:
            print("Multi-leg calculation failed.")
            print("Error:", error)


def compare_multi_routes_clicked(button):

    with multi_output:

        clear_output(wait=True)

        try:
            speed = float(speed_input.value)
            restrictions = list(restriction_dropdown.value)

            default_routes = calculate_itinerary_routes(
                voyage_stops,
                []
            )

            restricted_routes = calculate_itinerary_routes(
                voyage_stops,
                restrictions
            )

            comparison_rows = []

            for index, (default_route, restricted_route) in enumerate(
                zip(default_routes, restricted_routes),
                start=1
            ):

                default_distance = default_route["distance_nm"]
                restricted_distance = restricted_route["distance_nm"]

                comparison_rows.append({
                    "Leg": index,
                    "Origin": default_route["origin"],
                    "Destination": default_route["destination"],
                    "Unrestricted (NM)": round(
                        default_distance, 2
                    ),
                    "Restricted (NM)": round(
                        restricted_distance, 2
                    ),
                    "Difference (NM)": round(
                        restricted_distance - default_distance,
                        2
                    )
                })

            total_default = get_total_distance(default_routes)
            total_restricted = get_total_distance(restricted_routes)

            default_duration = calculate_duration(
                total_default,
                speed
            )

            restricted_duration = calculate_duration(
                total_restricted,
                speed
            )

            print("MULTI-LEG ROUTE COMPARISON")
            print("=" * 60)

            print(
                "Passage Restrictions:",
                ", ".join(restrictions) or "None"
            )

            print(f"Vessel Speed: {speed:.1f} knots")

            print("\nINDIVIDUAL LEG COMPARISON")

            display(
                pd.DataFrame(comparison_rows)
            )

            print("\nTOTAL VOYAGE COMPARISON")

            summary_df = pd.DataFrame({
                "Metric": [
                    "Total Distance (NM)",
                    "Sailing Time (Hours)",
                    "Sailing Duration (Days)"
                ],
                "Unrestricted Route": [
                    round(total_default, 2),
                    round(default_duration["hours"], 2),
                    round(default_duration["days"], 2)
                ],
                "Restricted Route": [
                    round(total_restricted, 2),
                    round(restricted_duration["hours"], 2),
                    round(restricted_duration["days"], 2)
                ],
                "Difference": [
                    round(
                        total_restricted - total_default,
                        2
                    ),
                    round(
                        restricted_duration["hours"]
                        - default_duration["hours"],
                        2
                    ),
                    round(
                        restricted_duration["days"]
                        - default_duration["days"],
                        2
                    )
                ]
            })

            display(summary_df)

            display(
                create_comparison_map(
                    default_routes,
                    restricted_routes,
                    voyage_stops
                )
            )

        except Exception as error:
            print("Multi-leg comparison failed.")
            print("Error:", error)


calculate_multi_button.on_click(calculate_multi_clicked)
compare_multi_button.on_click(compare_multi_routes_clicked)


# ============================================================
# 10. BUILD APPLICATION INTERFACE
# ============================================================

port_to_port_tab = widgets.VBox([
    widgets.HTML("<h3>Port-to-Port Voyage Planning</h3>"),
    origin_dropdown,
    destination_dropdown,
    widgets.HBox([
        port_route_button,
        port_compare_button
    ]),
    port_output
])

multi_leg_tab = widgets.VBox([
    widgets.HTML("<h3>Multi-Leg Voyage Planning</h3>"),
    stop_dropdown,
    widgets.HBox([
        add_stop_button,
        remove_stop_button,
        clear_stops_button
    ]),
    itinerary_output,
    widgets.HBox([
        calculate_multi_button,
        compare_multi_button
    ]),
    multi_output
])

tabs = widgets.Tab(
    children=[
        port_to_port_tab,
        multi_leg_tab
    ]
)

tabs.set_title(0, "Port-to-Port")
tabs.set_title(1, "Multi-Leg")


# ============================================================
# 11. DISPLAY APPLICATION
# ============================================================

display(
    widgets.HTML(
        """
        <h1>Maritime Voyage Planner</h1>
        <p>
            Project 6 — Maritime Distance and
            Voyage Calculation Service
        </p>
        <p>
            <b>Prototype:</b> Routes generated using
            the open-source searoute library.
            Distances and routes require validation
            before operational use.
        </p>
        """
    ),

    widgets.HTML("<h3>Voyage Settings</h3>"),

    speed_input,

    restriction_dropdown,

    widgets.HTML("<hr>"),

    tabs
)

display_itinerary()

print("\nMaritime Voyage Planner initialized successfully.")

Successfully loaded 29 active ports.

HTML(value='\n        <h1>Maritime Voyage Planner</h1>\n        <p>\n            Project 6 — Maritime Distance…

HTML(value='<h3>Voyage Settings</h3>')

BoundedFloatText(value=15.0, description='Vessel Speed (knots):', layout=Layout(width='350px'), max=40.0, min=…

Dropdown(description='Passage Restrictions:', layout=Layout(width='500px'), options=(('Automatic — No Restrict…

HTML(value='<hr>')

Tab(children=(VBox(children=(HTML(value='<h3>Port-to-Port Voyage Planning</h3>'), Dropdown(description='Origin…

Maritime Voyage Planner initialized successfully.

In [64]:
# ============================================================
# POSITION-TO-PORT VOYAGE PLANNER
# STEP 1: CREATE INPUT INTERFACE
# ============================================================

# Vessel latitude
position_latitude = widgets.BoundedFloatText(
    value=1.2903,
    min=-90,
    max=90,
    step=0.0001,
    description="Vessel Latitude:",
    style={"description_width": "initial"},
    layout=widgets.Layout(width="350px")
)

# Vessel longitude
position_longitude = widgets.BoundedFloatText(
    value=103.8519,
    min=-180,
    max=180,
    step=0.0001,
    description="Vessel Longitude:",
    style={"description_width": "initial"},
    layout=widgets.Layout(width="350px")
)

# Destination port
position_destination = widgets.Dropdown(
    options=port_options,
    description="Destination Port:",
    style={"description_width": "initial"},
    layout=widgets.Layout(width="400px")
)

# Calculate route button
position_route_button = widgets.Button(
    description="Calculate Position-to-Port Route",
    button_style="primary",
    icon="ship",
    layout=widgets.Layout(width="280px")
)

# Output area
position_output = widgets.Output()

# Display interface
display(
    widgets.HTML("<h3>Position-to-Port Voyage Planning</h3>"),
    position_latitude,
    position_longitude,
    position_destination,
    position_route_button,
    position_output
)

HTML(value='<h3>Position-to-Port Voyage Planning</h3>')

BoundedFloatText(value=1.2903, description='Vessel Latitude:', layout=Layout(width='350px'), max=90.0, min=-90…

BoundedFloatText(value=103.8519, description='Vessel Longitude:', layout=Layout(width='350px'), max=180.0, min…

Dropdown(description='Destination Port:', layout=Layout(width='400px'), options=(('Algeciras (Spain)', 'ESALG'…

Button(button_style='primary', description='Calculate Position-to-Port Route', icon='ship', layout=Layout(widt…

Output()

In [66]:
# ============================================================
# POSITION-TO-PORT VOYAGE PLANNER
# STEP 2: ROUTE CALCULATION AND VISUALIZATION
# ============================================================

def calculate_position_to_port(button):

    with position_output:

        clear_output(wait=True)

        try:
            # Retrieve inputs
            latitude = float(position_latitude.value)
            longitude = float(position_longitude.value)

            destination_id = position_destination.value
            destination = get_port(destination_id)

            speed = float(speed_input.value)
            restrictions = list(restriction_dropdown.value)

            # Validate inputs
            if not (-90 <= latitude <= 90):
                raise ValueError("Latitude must be between -90 and 90.")

            if not (-180 <= longitude <= 180):
                raise ValueError("Longitude must be between -180 and 180.")

            if speed <= 0:
                raise ValueError("Vessel speed must be greater than zero.")

            # Coordinates must be [longitude, latitude]
            vessel_coordinates = [longitude, latitude]
            destination_coordinates = get_coordinates(destination_id)

            # Calculate route
            route = sr.searoute(
                vessel_coordinates,
                destination_coordinates,
                units="naut",
                restrictions=restrictions
            )

            distance = float(route.properties["length"])

            if distance <= 0:
                raise ValueError("No valid maritime route was returned.")

            duration = calculate_duration(distance, speed)

            # Display results
            print("POSITION-TO-PORT VOYAGE SUMMARY")
            print("=" * 50)

            print(f"Vessel Position: {latitude:.4f}, {longitude:.4f}")
            print(f"Destination: {destination['port_name']}")
            print(f"Maritime Distance: {distance:,.2f} NM")
            print(f"Vessel Speed: {speed:.1f} knots")
            print(f"Estimated Sailing Time: {duration['hours']:.2f} hours")
            print(f"Estimated Sailing Duration: {duration['days']:.2f} days")
            print(f"Passage Restrictions: {', '.join(restrictions) or 'None'}")

            # Create map
            voyage_map = folium.Map(
                location=[latitude, longitude],
                zoom_start=3
            )

            route_coordinates = [
                [lat, lon]
                for lon, lat in route.geometry["coordinates"]
            ]

            # Draw route
            folium.PolyLine(
                locations=route_coordinates,
                color="blue",
                weight=4,
                tooltip=f"{distance:,.2f} NM"
            ).add_to(voyage_map)

            # Vessel marker
            folium.Marker(
                location=[latitude, longitude],
                popup="Current Vessel Position",
                tooltip="Vessel Position",
                icon=folium.Icon(color="green")
            ).add_to(voyage_map)

            # Destination marker
            folium.Marker(
                location=[
                    float(destination["approach_latitude"]),
                    float(destination["approach_longitude"])
                ],
                popup=destination["port_name"],
                tooltip="Destination Port",
                icon=folium.Icon(color="purple")
            ).add_to(voyage_map)

            # Fit map
            voyage_map.fit_bounds(
                route_coordinates + [
                    [latitude, longitude],
                    [
                        float(destination["approach_latitude"]),
                        float(destination["approach_longitude"])
                    ]
                ]
            )

            display(voyage_map)

        except Exception as error:
            print("Position-to-port calculation failed.")
            print("Error:", error)


# Connect button to calculation
position_route_button.on_click(calculate_position_to_port)

print("Position-to-Port routing engine connected successfully.")

Position-to-Port routing engine connected successfully.

In [68]:
# ============================================================
# POSITION-TO-PORT VOYAGE PLANNER
# STEP 4: ROUTE COMPARISON
# ============================================================

# 1. CREATE COMPARE ROUTES BUTTON

position_compare_button = widgets.Button(
    description="Compare Routes",
    button_style="info",
    icon="exchange",
    layout=widgets.Layout(width="180px")
)


# 2. CREATE ROUTE COMPARISON FUNCTION

def compare_position_to_port(button):

    with position_output:

        clear_output(wait=True)

        try:

            # Retrieve vessel coordinates
            latitude = float(position_latitude.value)
            longitude = float(position_longitude.value)

            # Retrieve destination
            destination_id = position_destination.value
            destination = get_port(destination_id)

            # Retrieve voyage settings
            speed = float(speed_input.value)
            restrictions = list(restriction_dropdown.value)

            # Validate inputs
            if not (-90 <= latitude <= 90):
                raise ValueError(
                    "Latitude must be between -90 and 90."
                )

            if not (-180 <= longitude <= 180):
                raise ValueError(
                    "Longitude must be between -180 and 180."
                )

            if speed <= 0:
                raise ValueError(
                    "Vessel speed must be greater than zero."
                )

            # Validate passage restriction selection
            if not restrictions:
                raise ValueError(
                    "Please select a passage restriction "
                    "before comparing routes."
                )

            # searoute requires [longitude, latitude]
            vessel_coordinates = [longitude, latitude]

            destination_coordinates = get_coordinates(
                destination_id
            )

            # ------------------------------------------------
            # CALCULATE UNRESTRICTED ROUTE
            # ------------------------------------------------

            unrestricted_route = sr.searoute(
                vessel_coordinates,
                destination_coordinates,
                units="naut",
                restrictions=[]
            )

            unrestricted_distance = float(
                unrestricted_route.properties["length"]
            )

            # ------------------------------------------------
            # CALCULATE RESTRICTED ROUTE
            # ------------------------------------------------

            restricted_route = sr.searoute(
                vessel_coordinates,
                destination_coordinates,
                units="naut",
                restrictions=restrictions
            )

            restricted_distance = float(
                restricted_route.properties["length"]
            )

            if unrestricted_distance <= 0 or restricted_distance <= 0:
                raise ValueError(
                    "One or both routes returned an invalid distance."
                )

            # ------------------------------------------------
            # CALCULATE SAILING DURATIONS
            # ------------------------------------------------

            unrestricted_duration = calculate_duration(
                unrestricted_distance,
                speed
            )

            restricted_duration = calculate_duration(
                restricted_distance,
                speed
            )

            distance_difference = (
                restricted_distance - unrestricted_distance
            )

            duration_difference = (
                restricted_duration["days"]
                - unrestricted_duration["days"]
            )

            # ------------------------------------------------
            # DISPLAY COMPARISON SUMMARY
            # ------------------------------------------------

            print("POSITION-TO-PORT ROUTE COMPARISON")
            print("=" * 60)

            print(
                f"Vessel Position: "
                f"{latitude:.4f}, {longitude:.4f}"
            )

            print(
                f"Destination: {destination['port_name']}"
            )

            print(f"Vessel Speed: {speed:.1f} knots")

            print(
                f"Selected Restrictions: "
                f"{', '.join(restrictions)}"
            )

            comparison_df = pd.DataFrame([
                {
                    "Route": "Unrestricted",
                    "Distance (NM)": round(
                        unrestricted_distance, 2
                    ),
                    "Duration (Days)": round(
                        unrestricted_duration["days"], 2
                    )
                },
                {
                    "Route": "Restricted",
                    "Distance (NM)": round(
                        restricted_distance, 2
                    ),
                    "Duration (Days)": round(
                        restricted_duration["days"], 2
                    )
                },
                {
                    "Route": "Difference",
                    "Distance (NM)": round(
                        distance_difference, 2
                    ),
                    "Duration (Days)": round(
                        duration_difference, 2
                    )
                }
            ])

            display(comparison_df)

            # ------------------------------------------------
            # CREATE COMPARISON MAP
            # ------------------------------------------------

            comparison_map = folium.Map(
                location=[latitude, longitude],
                zoom_start=3,
                tiles="OpenStreetMap"
            )

            # Convert GeoJSON coordinates
            unrestricted_coordinates = [
                [lat, lon]
                for lon, lat in unrestricted_route.geometry["coordinates"]
            ]

            restricted_coordinates = [
                [lat, lon]
                for lon, lat in restricted_route.geometry["coordinates"]
            ]

            # Unrestricted route — SOLID BLUE
            folium.PolyLine(
                locations=unrestricted_coordinates,
                color="blue",
                weight=4,
                opacity=0.85,
                tooltip=(
                    f"Unrestricted Route: "
                    f"{unrestricted_distance:,.2f} NM"
                )
            ).add_to(comparison_map)

            # Restricted route — SOLID RED
            folium.PolyLine(
                locations=restricted_coordinates,
                color="red",
                weight=4,
                opacity=0.85,
                tooltip=(
                    f"Restricted Route: "
                    f"{restricted_distance:,.2f} NM"
                )
            ).add_to(comparison_map)

            # ------------------------------------------------
            # ADD VESSEL AND DESTINATION MARKERS
            # ------------------------------------------------

            folium.Marker(
                location=[latitude, longitude],
                popup="Current Vessel Position",
                tooltip="Vessel Position",
                icon=folium.Icon(color="green")
            ).add_to(comparison_map)

            destination_location = [
                float(destination["approach_latitude"]),
                float(destination["approach_longitude"])
            ]

            folium.Marker(
                location=destination_location,
                popup=destination["port_name"],
                tooltip="Destination Port",
                icon=folium.Icon(color="purple")
            ).add_to(comparison_map)

            # ------------------------------------------------
            # ADD MAP LEGEND
            # ------------------------------------------------

            legend_html = """
            <div style="
                position: fixed;
                bottom: 30px;
                left: 30px;
                z-index: 9999;
                background-color: white;
                border: 2px solid grey;
                border-radius: 6px;
                padding: 12px;
                font-size: 13px;
                color: black;
            ">
                <b>Route Comparison</b><br><br>

                <span style="color: blue;">
                    ━━━━━
                </span>
                Unrestricted Route<br>

                <span style="color: red;">
                    ━━━━━
                </span>
                Restricted Route
            </div>
            """

            comparison_map.get_root().html.add_child(
                folium.Element(legend_html)
            )

            # ------------------------------------------------
            # FIT MAP TO BOTH ROUTES
            # ------------------------------------------------

            all_coordinates = (
                unrestricted_coordinates
                + restricted_coordinates
                + [[latitude, longitude]]
                + [destination_location]
            )

            comparison_map.fit_bounds(all_coordinates)

            display(comparison_map)

        except Exception as error:

            print("Position-to-port route comparison failed.")
            print("Error:", error)


# 3. CONNECT COMPARE BUTTON

position_compare_button.on_click(
    compare_position_to_port
)


# 4. DISPLAY BOTH BUTTONS TOGETHER

display(
    widgets.HTML(
        "<h3>Position-to-Port Voyage Planning</h3>"
    ),

    position_latitude,

    position_longitude,

    position_destination,

    widgets.HBox([
        position_route_button,
        position_compare_button
    ]),

    position_output
)

print("Position-to-Port route comparison connected successfully.")

HTML(value='<h3>Position-to-Port Voyage Planning</h3>')

BoundedFloatText(value=1.2903, description='Vessel Latitude:', layout=Layout(width='350px'), max=90.0, min=-90…

BoundedFloatText(value=103.8519, description='Vessel Longitude:', layout=Layout(width='350px'), max=180.0, min…

Dropdown(description='Destination Port:', layout=Layout(width='400px'), options=(('Algeciras (Spain)', 'ESALG'…

HBox(children=(Button(button_style='primary', description='Calculate Position-to-Port Route', icon='ship', lay…

Output(outputs=({'name': 'stdout', 'text': 'POSITION-TO-PORT VOYAGE SUMMARY\n=================================…

Position-to-Port route comparison connected successfully.

In [70]:
# ============================================================
# VOYAGE PLANNER — CONSOLIDATED THREE-TAB INTERFACE
# ============================================================

# ------------------------------------------------------------
# TAB 1: PORT-TO-PORT
# ------------------------------------------------------------

port_to_port_tab = widgets.VBox([

    widgets.HTML(
        "<h3>Port-to-Port Voyage Planning</h3>"
    ),

    widgets.HTML(
        "<p>Calculate and compare maritime routes "
        "between two selected ports.</p>"
    ),

    origin_dropdown,

    destination_dropdown,

    widgets.HBox([
        port_route_button,
        port_compare_button
    ]),

    port_output

])


# ------------------------------------------------------------
# TAB 2: MULTI-LEG
# ------------------------------------------------------------

multi_leg_tab = widgets.VBox([

    widgets.HTML(
        "<h3>Multi-Leg Voyage Planning</h3>"
    ),

    widgets.HTML(
        "<p>Build a voyage itinerary with multiple "
        "port stops and compare alternative routes.</p>"
    ),

    stop_dropdown,

    widgets.HBox([
        add_stop_button,
        remove_stop_button,
        clear_stops_button
    ]),

    itinerary_output,

    widgets.HBox([
        calculate_multi_button,
        compare_multi_button
    ]),

    multi_output

])


# ------------------------------------------------------------
# TAB 3: POSITION-TO-PORT
# ------------------------------------------------------------

position_to_port_tab = widgets.VBox([

    widgets.HTML(
        "<h3>Position-to-Port Voyage Planning</h3>"
    ),

    widgets.HTML(
        "<p>Enter the vessel's current coordinates "
        "and calculate or compare maritime routes "
        "to a selected destination port.</p>"
    ),

    position_latitude,

    position_longitude,

    position_destination,

    widgets.HBox([
        position_route_button,
        position_compare_button
    ]),

    position_output

])


# ------------------------------------------------------------
# CREATE CONSOLIDATED INTERFACE
# ------------------------------------------------------------

voyage_tabs = widgets.Tab(

    children=[
        port_to_port_tab,
        multi_leg_tab,
        position_to_port_tab
    ]

)

voyage_tabs.set_title(0, "Port-to-Port")
voyage_tabs.set_title(1, "Multi-Leg")
voyage_tabs.set_title(2, "Position-to-Port")


# ------------------------------------------------------------
# DISPLAY APPLICATION
# ------------------------------------------------------------

display(

    widgets.HTML(
        "<h2>Maritime Voyage Planner</h2>"
    ),

    widgets.HTML(
        "<p>Select a voyage-planning mode below.</p>"
    ),

    widgets.HTML(
        "<h3>Voyage Settings</h3>"
    ),

    speed_input,

    restriction_dropdown,

    voyage_tabs

)

# Refresh the multi-leg itinerary display
display_itinerary()

HTML(value='<h2>Maritime Voyage Planner</h2>')

HTML(value='<p>Select a voyage-planning mode below.</p>')

HTML(value='<h3>Voyage Settings</h3>')

BoundedFloatText(value=15.0, description='Vessel Speed (knots):', layout=Layout(width='350px'), max=40.0, min=…

Dropdown(description='Passage Restrictions:', index=3, layout=Layout(width='500px'), options=(('Automatic — No…

Tab(children=(VBox(children=(HTML(value='<h3>Port-to-Port Voyage Planning</h3>'), HTML(value='<p>Calculate and…

In [72]:
%pip install streamlit

Requirement already satisfied: streamlit in /opt/anaconda3/lib/python3.12/site-packages (1.32.0)
Requirement already satisfied: altair<6,>=4.0 in /opt/anaconda3/lib/python3.12/site-packages (from streamlit) (5.0.1)
Requirement already satisfied: blinker<2,>=1.0.0 in /opt/anaconda3/lib/python3.12/site-packages (from streamlit) (1.6.2)
Requirement already satisfied: cachetools<6,>=4.0 in /opt/anaconda3/lib/python3.12/site-packages (from streamlit) (5.3.3)
Requirement already satisfied: click<9,>=7.0 in /opt/anaconda3/lib/python3.12/site-packages (from streamlit) (8.1.7)
Requirement already satisfied: numpy<2,>=1.19.3 in /opt/anaconda3/lib/python3.12/site-packages (from streamlit) (1.26.4)
Requirement already satisfied: packaging<24,>=16.8 in /opt/anaconda3/lib/python3.12/site-packages (from streamlit) (23.2)
Requirement already satisfied: pandas<3,>=1.3.0 in /opt/anaconda3/lib/python3.12/site-packages (from streamlit) (2.2.2)
Requirement already satisfied: pillow<11,>=7.1.0 in /opt/anaconda3/lib/python3.12/site-packages (from streamlit) (10.3.0)
Requirement already satisfied: protobuf<5,>=3.20 in /opt/anaconda3/lib/python3.12/site-packages (from streamlit) (3.20.3)
Requirement already satisfied: pyarrow>=7.0 in /opt/anaconda3/lib/python3.12/site-packages (from streamlit) (14.0.2)
Requirement already satisfied: requests<3,>=2.27 in /opt/anaconda3/lib/python3.12/site-packages (from streamlit) (2.32.2)
Requirement already satisfied: rich<14,>=10.14.0 in /opt/anaconda3/lib/python3.12/site-packages (from streamlit) (13.3.5)
Requirement already satisfied: tenacity<9,>=8.1.0 in /opt/anaconda3/lib/python3.12/site-packages (from streamlit) (8.2.2)
Requirement already satisfied: toml<2,>=0.10.1 in /opt/anaconda3/lib/python3.12/site-packages (from streamlit) (0.10.2)
Requirement already satisfied: typing-extensions<5,>=4.3.0 in /opt/anaconda3/lib/python3.12/site-packages (from streamlit) (4.11.0)
Requirement already satisfied: gitpython!=3.1.19,<4,>=3.0.7 in /opt/anaconda3/lib/python3.12/site-packages (from streamlit) (3.1.37)
Requirement already satisfied: pydeck<1,>=0.8.0b4 in /opt/anaconda3/lib/python3.12/site-packages (from streamlit) (0.8.0)
Requirement already satisfied: tornado<7,>=6.0.3 in /opt/anaconda3/lib/python3.12/site-packages (from streamlit) (6.4.1)
Requirement already satisfied: jinja2 in /opt/anaconda3/lib/python3.12/site-packages (from altair<6,>=4.0->streamlit) (3.1.4)
Requirement already satisfied: jsonschema>=3.0 in /opt/anaconda3/lib/python3.12/site-packages (from altair<6,>=4.0->streamlit) (4.19.2)
Requirement already satisfied: toolz in /opt/anaconda3/lib/python3.12/site-packages (from altair<6,>=4.0->streamlit) (0.12.0)
Requirement already satisfied: gitdb<5,>=4.0.1 in /opt/anaconda3/lib/python3.12/site-packages (from gitpython!=3.1.19,<4,>=3.0.7->streamlit) (4.0.7)
Requirement already satisfied: python-dateutil>=2.8.2 in /opt/anaconda3/lib/python3.12/site-packages (from pandas<3,>=1.3.0->streamlit) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in /opt/anaconda3/lib/python3.12/site-packages (from pandas<3,>=1.3.0->streamlit) (2024.1)
Requirement already satisfied: tzdata>=2022.7 in /opt/anaconda3/lib/python3.12/site-packages (from pandas<3,>=1.3.0->streamlit) (2023.3)
Requirement already satisfied: charset-normalizer<4,>=2 in /opt/anaconda3/lib/python3.12/site-packages (from requests<3,>=2.27->streamlit) (2.0.4)
Requirement already satisfied: idna<4,>=2.5 in /opt/anaconda3/lib/python3.12/site-packages (from requests<3,>=2.27->streamlit) (3.7)
Requirement already satisfied: urllib3<3,>=1.21.1 in /opt/anaconda3/lib/python3.12/site-packages (from requests<3,>=2.27->streamlit) (2.2.2)
Requirement already satisfied: certifi>=2017.4.17 in /opt/anaconda3/lib/python3.12/site-packages (from requests<3,>=2.27->streamlit) (2024.7.4)
Requirement already satisfied: markdown-it-py<3.0.0,>=2.2.0 in /opt/anaconda3/lib/python3.12/site-packages (from rich<14,>=10.14.0->streamlit) (2.2.0)
Requirement already satisfied: pygments<3.0.0,>=2.13.0 in /opt/anaconda3/lib/python3.12/site-packages (from rich<14,>=10.14.0->streamlit) (2.15.1)
Requirement already satisfied: smmap<5,>=3.0.1 in /opt/anaconda3/lib/python3.12/site-packages (from gitdb<5,>=4.0.1->gitpython!=3.1.19,<4,>=3.0.7->streamlit) (4.0.0)
Requirement already satisfied: MarkupSafe>=2.0 in /opt/anaconda3/lib/python3.12/site-packages (from jinja2->altair<6,>=4.0->streamlit) (2.1.3)
Requirement already satisfied: attrs>=22.2.0 in /opt/anaconda3/lib/python3.12/site-packages (from jsonschema>=3.0->altair<6,>=4.0->streamlit) (23.1.0)
Requirement already satisfied: jsonschema-specifications>=2023.03.6 in /opt/anaconda3/lib/python3.12/site-packages (from jsonschema>=3.0->altair<6,>=4.0->streamlit) (2023.7.1)
Requirement already satisfied: referencing>=0.28.4 in /opt/anaconda3/lib/python3.12/site-packages (from jsonschema>=3.0->altair<6,>=4.0->streamlit) (0.30.2)
Requirement already satisfied: rpds-py>=0.7.1 in /opt/anaconda3/lib/python3.12/site-packages (from jsonschema>=3.0->altair<6,>=4.0->streamlit) (0.10.6)
Requirement already satisfied: mdurl~=0.1 in /opt/anaconda3/lib/python3.12/site-packages (from markdown-it-py<3.0.0,>=2.2.0->rich<14,>=10.14.0->streamlit) (0.1.0)
Requirement already satisfied: six>=1.5 in /opt/anaconda3/lib/python3.12/site-packages (from python-dateutil>=2.8.2->pandas<3,>=1.3.0->streamlit) (1.16.0)
Note: you may need to restart the kernel to use updated packages.

In [74]:
import streamlit as st

print("Streamlit version:", st.__version__)
print("Streamlit installed successfully!")

Streamlit version: 1.32.0
Streamlit installed successfully!

In [76]:
%%writefile app.py

import streamlit as st

st.set_page_config(
    page_title="Maritime Voyage Planner",
    page_icon="🚢",
    layout="wide"
)

st.title("🚢 Maritime Voyage Planner")

st.write("Welcome to the Maritime Voyage Planner.")

tab1, tab2, tab3 = st.tabs([
    "Port-to-Port",
    "Multi-Leg",
    "Position-to-Port"
])

with tab1:
    st.header("Port-to-Port Voyage Planning")
    st.write("Calculate and compare routes between two ports.")

with tab2:
    st.header("Multi-Leg Voyage Planning")
    st.write("Plan voyages with multiple port stops.")

with tab3:
    st.header("Position-to-Port Voyage Planning")
    st.write("Calculate routes from vessel coordinates to a destination port.")

Writing app.py

In [78]:
%%writefile app.py

import streamlit as st
import pandas as pd
import folium
import searoute as sr

from pathlib import Path
from streamlit.components.v1 import html


# ============================================================
# APPLICATION CONFIGURATION
# ============================================================

st.set_page_config(
    page_title="Maritime Voyage Planner",
    page_icon="🚢",
    layout="wide"
)

st.title("🚢 Maritime Voyage Planner")


# ============================================================
# LOAD PORT DATASET
# ============================================================

DATASET_PATH = Path("voyage_planner_datasets_20261006.xlsx")

@st.cache_data
def load_ports():

    df = pd.read_excel(
        DATASET_PATH,
        sheet_name="Port Reference"
    )

    df = df[
        df["status"].astype(str).str.lower() == "active"
    ].copy()

    df = df.sort_values("port_name")

    return df


try:
    ports_df = load_ports()

except Exception as error:
    st.error(f"Failed to load port dataset: {error}")
    st.stop()


port_options = {
    f"{row['port_name']} ({row['country']})": row
    for _, row in ports_df.iterrows()
}

port_names = list(port_options.keys())


# ============================================================
# VOYAGE SETTINGS
# ============================================================

st.subheader("Voyage Settings")

speed = st.number_input(
    "Vessel Speed (knots)",
    min_value=0.1,
    max_value=50.0,
    value=15.0,
    step=0.5
)

restriction_options = {
    "Automatic — No Restrictions": [],
    "Avoid Suez Canal": ["suez"],
    "Avoid Panama Canal": ["panama"],
    "Avoid Suez and Panama Canals": ["suez", "panama"],
    "Avoid Suez, Panama and Northwest Passage": [
        "suez", "panama", "northwest"
    ]
}

restriction_selection = st.selectbox(
    "Passage Restrictions",
    list(restriction_options.keys())
)

restrictions = restriction_options[restriction_selection]


# ============================================================
# ROUTING FUNCTIONS
# ============================================================

def get_coordinates(port):

    return [
        float(port["approach_longitude"]),
        float(port["approach_latitude"])
    ]


def calculate_route(origin, destination):

    route = sr.searoute(
        get_coordinates(origin),
        get_coordinates(destination),
        units="naut",
        restrictions=restrictions
    )

    distance = float(route.properties["length"])

    duration_hours = distance / speed
    duration_days = duration_hours / 24

    return route, distance, duration_hours, duration_days


def create_route_map(route, origin, destination):

    coordinates = [
        [lat, lon]
        for lon, lat in route.geometry["coordinates"]
    ]

    voyage_map = folium.Map(
        location=coordinates[0],
        zoom_start=3
    )

    folium.PolyLine(
        coordinates,
        color="blue",
        weight=4,
        tooltip="Maritime Route"
    ).add_to(voyage_map)

    folium.Marker(
        [
            float(origin["approach_latitude"]),
            float(origin["approach_longitude"])
        ],
        tooltip="Origin",
        popup=origin["port_name"],
        icon=folium.Icon(color="green")
    ).add_to(voyage_map)

    folium.Marker(
        [
            float(destination["approach_latitude"]),
            float(destination["approach_longitude"])
        ],
        tooltip="Destination",
        popup=destination["port_name"],
        icon=folium.Icon(color="purple")
    ).add_to(voyage_map)

    voyage_map.fit_bounds(coordinates)

    return voyage_map


# ============================================================
# APPLICATION TABS
# ============================================================

tab1, tab2, tab3 = st.tabs([
    "Port-to-Port",
    "Multi-Leg",
    "Position-to-Port"
])


# ============================================================
# TAB 1 — PORT-TO-PORT
# ============================================================

with tab1:

    st.header("Port-to-Port Voyage Planning")

    origin_name = st.selectbox(
        "Origin Port",
        port_names,
        key="origin"
    )

    destination_name = st.selectbox(
        "Destination Port",
        port_names,
        key="destination",
        index=min(1, len(port_names) - 1)
    )

    if st.button("Calculate Route", key="calculate_port"):

        try:

            if origin_name == destination_name:
                st.error(
                    "Origin and destination ports must be different."
                )

            else:

                origin = port_options[origin_name]
                destination = port_options[destination_name]

                route, distance, hours, days = calculate_route(
                    origin,
                    destination
                )

                st.success("Route calculated successfully!")

                col1, col2, col3 = st.columns(3)

                col1.metric(
                    "Maritime Distance",
                    f"{distance:,.2f} NM"
                )

                col2.metric(
                    "Sailing Time",
                    f"{hours:,.2f} hours"
                )

                col3.metric(
                    "Sailing Duration",
                    f"{days:,.2f} days"
                )

                voyage_map = create_route_map(
                    route,
                    origin,
                    destination
                )

                html(
                    voyage_map._repr_html_(),
                    height=550
                )

        except Exception as error:

            st.error(f"Route calculation failed: {error}")


# ============================================================
# TAB 2 — MULTI-LEG
# ============================================================

with tab2:

    st.header("Multi-Leg Voyage Planning")

    st.info(
        "Multi-Leg functionality will be migrated next."
    )


# ============================================================
# TAB 3 — POSITION-TO-PORT
# ============================================================

with tab3:

    st.header("Position-to-Port Voyage Planning")

    st.info(
        "Position-to-Port functionality will be migrated after Multi-Leg."
    )

Overwriting app.py

In [80]:
from pathlib import Path

app_path = Path("app.py")
app_code = app_path.read_text(encoding="utf-8")

old_section = '''# ============================================================
# TAB 2 — MULTI-LEG
# ============================================================

with tab2:

    st.header("Multi-Leg Voyage Planning")

    st.info(
        "Multi-Leg functionality will be migrated next."
    )
'''

new_section = '''# ============================================================
# TAB 2 — MULTI-LEG
# ============================================================

with tab2:

    st.header("Multi-Leg Voyage Planning")

    st.write(
        "Select multiple ports to create a voyage itinerary."
    )

    # Initialize itinerary
    if "voyage_stops" not in st.session_state:
        st.session_state.voyage_stops = []

    # Port selection
    selected_stop = st.selectbox(
        "Select Port",
        port_names,
        key="multi_stop"
    )

    # Itinerary controls
    col1, col2, col3 = st.columns(3)

    with col1:
        if st.button("Add Stop", key="add_stop"):
            if (
                st.session_state.voyage_stops
                and st.session_state.voyage_stops[-1] == selected_stop
            ):
                st.warning("Consecutive duplicate ports are not allowed.")
            else:
                st.session_state.voyage_stops.append(selected_stop)

    with col2:
        if st.button("Remove Last Stop", key="remove_stop"):
            if st.session_state.voyage_stops:
                st.session_state.voyage_stops.pop()

    with col3:
        if st.button("Clear Itinerary", key="clear_stops"):
            st.session_state.voyage_stops = []

    # Display itinerary
    st.subheader("Current Itinerary")

    if st.session_state.voyage_stops:
        for index, port in enumerate(
            st.session_state.voyage_stops,
            start=1
        ):
            st.write(f"{index}. {port}")
    else:
        st.info("No ports added yet.")

    # Calculate multi-leg voyage
    if st.button(
        "Calculate Multi-Leg Voyage",
        key="calculate_multi"
    ):

        if len(st.session_state.voyage_stops) < 2:
            st.error("Please add at least two ports.")

        else:
            try:

                stops = st.session_state.voyage_stops

                leg_results = []
                all_coordinates = []

                total_distance = 0

                voyage_map = folium.Map(
                    location=[0, 0],
                    zoom_start=2
                )

                route_colors = [
                    "blue", "red", "green",
                    "purple", "orange", "darkblue"
                ]

                for i in range(len(stops) - 1):

                    origin = port_options[stops[i]]
                    destination = port_options[stops[i + 1]]

                    route, distance, hours, days = calculate_route(
                        origin,
                        destination
                    )

                    total_distance += distance

                    coordinates = [
                        [lat, lon]
                        for lon, lat in route.geometry["coordinates"]
                    ]

                    all_coordinates.extend(coordinates)

                    folium.PolyLine(
                        locations=coordinates,
                        color=route_colors[i % len(route_colors)],
                        weight=4,
                        tooltip=f"Leg {i + 1}: {distance:,.2f} NM"
                    ).add_to(voyage_map)

                    leg_results.append({
                        "Leg": i + 1,
                        "Origin": origin["port_name"],
                        "Destination": destination["port_name"],
                        "Distance (NM)": round(distance, 2),
                        "Duration (Days)": round(days, 2)
                    })

                # Add port markers
                for i, port_name in enumerate(stops):

                    port = port_options[port_name]

                    location = [
                        float(port["approach_latitude"]),
                        float(port["approach_longitude"])
                    ]

                    marker_color = (
                        "green" if i == 0
                        else "purple" if i == len(stops) - 1
                        else "blue"
                    )

                    folium.Marker(
                        location=location,
                        popup=f"Stop {i + 1}: {port['port_name']}",
                        icon=folium.Icon(color=marker_color)
                    ).add_to(voyage_map)

                total_hours = total_distance / speed
                total_days = total_hours / 24

                st.success("Multi-leg voyage calculated successfully!")

                col1, col2, col3 = st.columns(3)

                col1.metric(
                    "Total Distance",
                    f"{total_distance:,.2f} NM"
                )

                col2.metric(
                    "Total Sailing Time",
                    f"{total_hours:,.2f} hours"
                )

                col3.metric(
                    "Total Sailing Duration",
                    f"{total_days:,.2f} days"
                )

                st.subheader("Leg-by-Leg Breakdown")

                st.dataframe(
                    pd.DataFrame(leg_results),
                    use_container_width=True
                )

                voyage_map.fit_bounds(all_coordinates)

                html(
                    voyage_map._repr_html_(),
                    height=550
                )

            except Exception as error:
                st.error(f"Multi-leg calculation failed: {error}")
'''

if old_section not in app_code:
    raise ValueError(
        "Multi-Leg placeholder not found. "
        "No changes were made to app.py."
    )

app_code = app_code.replace(old_section, new_section, 1)

app_path.write_text(app_code, encoding="utf-8")

print("Multi-Leg functionality added successfully!")

Multi-Leg functionality added successfully!

In [82]:
from pathlib import Path

app_path = Path("app.py")
app_code = app_path.read_text(encoding="utf-8")

old_section = '''# ============================================================
# TAB 3 — POSITION-TO-PORT
# ============================================================

with tab3:

    st.header("Position-to-Port Voyage Planning")

    st.info(
        "Position-to-Port functionality will be migrated after Multi-Leg."
    )
'''

new_section = '''# ============================================================
# TAB 3 — POSITION-TO-PORT
# ============================================================

with tab3:

    st.header("Position-to-Port Voyage Planning")

    st.write(
        "Enter the vessel's current coordinates and select "
        "a destination port."
    )

    # Vessel position inputs
    latitude = st.number_input(
        "Vessel Latitude",
        min_value=-90.0,
        max_value=90.0,
        value=1.2903,
        format="%.4f",
        key="position_latitude"
    )

    longitude = st.number_input(
        "Vessel Longitude",
        min_value=-180.0,
        max_value=180.0,
        value=103.8519,
        format="%.4f",
        key="position_longitude"
    )

    # Destination selection
    position_destination_name = st.selectbox(
        "Destination Port",
        port_names,
        key="position_destination"
    )

    if st.button(
        "Calculate Position-to-Port Route",
        key="calculate_position"
    ):

        try:

            destination = port_options[
                position_destination_name
            ]

            # searoute requires [longitude, latitude]
            vessel_coordinates = [
                float(longitude),
                float(latitude)
            ]

            destination_coordinates = get_coordinates(
                destination
            )

            # Calculate maritime route
            route = sr.searoute(
                vessel_coordinates,
                destination_coordinates,
                units="naut",
                restrictions=restrictions
            )

            distance = float(
                route.properties["length"]
            )

            if distance <= 0:
                raise ValueError(
                    "No valid maritime route was returned."
                )

            # Calculate sailing duration
            hours = distance / speed
            days = hours / 24

            st.success(
                "Position-to-Port route calculated successfully!"
            )

            # Display results
            col1, col2, col3 = st.columns(3)

            col1.metric(
                "Maritime Distance",
                f"{distance:,.2f} NM"
            )

            col2.metric(
                "Sailing Time",
                f"{hours:,.2f} hours"
            )

            col3.metric(
                "Sailing Duration",
                f"{days:,.2f} days"
            )

            # Create interactive map
            route_coordinates = [
                [lat, lon]
                for lon, lat in route.geometry["coordinates"]
            ]

            if not route_coordinates:
                raise ValueError(
                    "No route coordinates were returned."
                )

            voyage_map = folium.Map(
                location=[latitude, longitude],
                zoom_start=3
            )

            # Draw maritime route
            folium.PolyLine(
                locations=route_coordinates,
                color="blue",
                weight=4,
                tooltip=f"Maritime Distance: {distance:,.2f} NM"
            ).add_to(voyage_map)

            # Vessel position marker
            folium.Marker(
                location=[latitude, longitude],
                popup="Current Vessel Position",
                tooltip="Vessel Position",
                icon=folium.Icon(color="green")
            ).add_to(voyage_map)

            # Destination marker
            destination_location = [
                float(destination["approach_latitude"]),
                float(destination["approach_longitude"])
            ]

            folium.Marker(
                location=destination_location,
                popup=destination["port_name"],
                tooltip="Destination Port",
                icon=folium.Icon(color="purple")
            ).add_to(voyage_map)

            # Fit map to route
            voyage_map.fit_bounds(
                route_coordinates
                + [[latitude, longitude]]
                + [destination_location]
            )

            html(
                voyage_map._repr_html_(),
                height=550
            )

        except Exception as error:

            st.error(
                f"Position-to-Port calculation failed: {error}"
            )
'''

if old_section not in app_code:
    raise ValueError(
        "Position-to-Port placeholder not found. "
        "No changes were made to app.py."
    )

app_code = app_code.replace(
    old_section,
    new_section,
    1
)

app_path.write_text(
    app_code,
    encoding="utf-8"
)

print("Position-to-Port functionality added successfully!")

Position-to-Port functionality added successfully!

In [99]:
from pathlib import Path

app_code = Path("app.py").read_text(encoding="utf-8")
lines = app_code.splitlines()

print("Total lines in app.py:", len(lines))

for i, line in enumerate(lines):
    if "_repr_html_" in line or "html(" in line:
        print(f"\n--- Found at line {i + 1} ---")

        start = max(0, i - 5)
        end = min(len(lines), i + 6)

        for j in range(start, end):
            print(f"{j + 1}: {lines[j]}")

Total lines in app.py: 1048

--- Found at line 413 ---
408:                     route,
409:                     origin,
410:                     destination
411:                 )
412:
413:                 html(
414:                     voyage_map._repr_html_(),
415:                     height=550
416:                 )
417:
418:         except Exception as error:

--- Found at line 414 ---
409:                     origin,
410:                     destination
411:                 )
412:
413:                 html(
414:                     voyage_map._repr_html_(),
415:                     height=550
416:                 )
417:
418:         except Exception as error:
419:

--- Found at line 494 ---
489:                     [unrestricted],
490:                     [restricted],
491:                     markers
492:                 )
493:
494:                 html(
495:                     comparison_map._repr_html_(),
496:                     height=550
497:                 )
498:
499:         except Exception as error:

--- Found at line 495 ---
490:                     [restricted],
491:                     markers
492:                 )
493:
494:                 html(
495:                     comparison_map._repr_html_(),
496:                     height=550
497:                 )
498:
499:         except Exception as error:
500:

--- Found at line 677 ---
672:                     use_container_width=True
673:                 )
674:
675:                 voyage_map.fit_bounds(all_coordinates)
676:
677:                 html(
678:                     voyage_map._repr_html_(),
679:                     height=550
680:                 )
681:
682:             except Exception as error:

--- Found at line 678 ---
673:                 )
674:
675:                 voyage_map.fit_bounds(all_coordinates)
676:
677:                 html(
678:                     voyage_map._repr_html_(),
679:                     height=550
680:                 )
681:
682:             except Exception as error:
683:                 st.error(f"Multi-leg calculation failed: {error}")

--- Found at line 791 ---
786:                     unrestricted_routes,
787:                     restricted_routes,
788:                     markers
789:                 )
790:
791:                 html(
792:                     comparison_map._repr_html_(),
793:                     height=550
794:                 )
795:
796:             except Exception as error:

--- Found at line 792 ---
787:                     restricted_routes,
788:                     markers
789:                 )
790:
791:                 html(
792:                     comparison_map._repr_html_(),
793:                     height=550
794:                 )
795:
796:             except Exception as error:
797:

--- Found at line 956 ---
951:                 route_coordinates
952:                 + [[latitude, longitude]]
953:                 + [destination_location]
954:             )
955:
956:             html(
957:                 voyage_map._repr_html_(),
958:                 height=550
959:             )
960:
961:         except Exception as error:

--- Found at line 957 ---
952:                 + [[latitude, longitude]]
953:                 + [destination_location]
954:             )
955:
956:             html(
957:                 voyage_map._repr_html_(),
958:                 height=550
959:             )
960:
961:         except Exception as error:
962:

--- Found at line 1039 ---
1034:                     [unrestricted],
1035:                     [restricted],
1036:                     markers
1037:                 )
1038:
1039:                 html(
1040:                     comparison_map._repr_html_(),
1041:                     height=550
1042:                 )
1043:
1044:         except Exception as error:

--- Found at line 1040 ---
1035:                     [restricted],
1036:                     markers
1037:                 )
1038:
1039:                 html(
1040:                     comparison_map._repr_html_(),
1041:                     height=550
1042:                 )
1043:
1044:         except Exception as error:
1045:

In [101]:
from pathlib import Path

lines = Path("app.py").read_text(encoding="utf-8").splitlines()

print("MAP DISPLAY LOCATIONS")
print("=" * 50)

for i, line in enumerate(lines):
    if "_repr_html_" in line:
        print(f"\nMap found at line {i + 1}")

        for j in range(max(0, i - 2), min(len(lines), i + 4)):
            print(f"{j + 1}: {lines[j]}")

MAP DISPLAY LOCATIONS
==================================================

Map found at line 414
412:
413:                 html(
414:                     voyage_map._repr_html_(),
415:                     height=550
416:                 )
417:

Map found at line 495
493:
494:                 html(
495:                     comparison_map._repr_html_(),
496:                     height=550
497:                 )
498:

Map found at line 678
676:
677:                 html(
678:                     voyage_map._repr_html_(),
679:                     height=550
680:                 )
681:

Map found at line 792
790:
791:                 html(
792:                     comparison_map._repr_html_(),
793:                     height=550
794:                 )
795:

Map found at line 957
955:
956:             html(
957:                 voyage_map._repr_html_(),
958:                 height=550
959:             )
960:

Map found at line 1040
1038:
1039:                 html(
1040:                     comparison_map._repr_html_(),
1041:                     height=550
1042:                 )
1043:

In [105]:
from pathlib import Path
import shutil
import textwrap

# ============================================================
# STEP 7 — INSTALL CSV / JSON EXPORTS
# ============================================================

app_path = Path("app.py")
original_code = app_path.read_text(encoding="utf-8")

if "# EXPORT FUNCTIONS — STEP 7" in original_code:
    raise ValueError("Export functionality is already installed.")

# ------------------------------------------------------------
# 1. SHARED EXPORT FUNCTIONS
# ------------------------------------------------------------

export_functions = '''
# ============================================================
# EXPORT FUNCTIONS — STEP 7
# ============================================================

def export_voyage_results(voyage_type, voyage_mode, rows, itinerary=None,
                          vessel_position=None):

    payload = {
        "voyage_type": voyage_type,
        "voyage_mode": voyage_mode,
        "vessel_speed_knots": float(speed),
        "passage_restrictions": list(restrictions),
        "itinerary": itinerary,
        "vessel_position": vessel_position,
        "results": rows
    }

    csv_rows = []

    for row in rows:
        csv_rows.append({
            "Voyage Type": voyage_type,
            "Voyage Mode": voyage_mode,
            "Vessel Speed (knots)": float(speed),
            "Passage Restrictions": ", ".join(restrictions),
            **row
        })

    csv_data = pd.DataFrame(csv_rows).to_csv(index=False)

    json_data = json.dumps(
        payload,
        indent=4,
        ensure_ascii=False
    )

    st.subheader("Export Voyage Results")

    col1, col2 = st.columns(2)

    with col1:
        st.download_button(
            "Download CSV",
            data=csv_data,
            file_name=f"{voyage_type.lower().replace('-', '_')}_{voyage_mode.lower()}.csv",
            mime="text/csv",
            key=f"export_{voyage_type}_{voyage_mode}_csv"
        )

    with col2:
        st.download_button(
            "Download JSON",
            data=json_data,
            file_name=f"{voyage_type.lower().replace('-', '_')}_{voyage_mode.lower()}.json",
            mime="application/json",
            key=f"export_{voyage_type}_{voyage_mode}_json"
        )
'''

# ------------------------------------------------------------
# 2. EXPORT BLOCKS FOR ALL SIX MAPS
# ------------------------------------------------------------

export_blocks = {

    414: '''
export_voyage_results(
    "Port-to-Port",
    "Standard",
    [{
        "Origin": origin["port_name"],
        "Destination": destination["port_name"],
        "Distance (NM)": round(distance, 2),
        "Duration (Hours)": round(hours, 2),
        "Duration (Days)": round(days, 2)
    }],
    itinerary=[origin["port_name"], destination["port_name"]]
)
''',

    495: '''
export_voyage_results(
    "Port-to-Port",
    "Comparison",
    [
        {
            "Route": label,
            "Origin": origin["port_name"],
            "Destination": destination["port_name"],
            "Distance (NM)": round(result["distance"], 2),
            "Duration (Days)": round(result["days"], 2)
        }
        for label, result in [
            ("Unrestricted", unrestricted),
            ("Restricted", restricted)
        ]
    ],
    itinerary=[origin["port_name"], destination["port_name"]]
)
''',

    678: '''
export_voyage_results(
    "Multi-Leg",
    "Standard",
    [
        {
            "Leg": row["Leg"],
            "Origin": row["Origin"],
            "Destination": row["Destination"],
            "Distance (NM)": row["Distance (NM)"],
            "Duration (Days)": row["Duration (Days)"]
        }
        for row in leg_results
    ] + [{
        "Leg": "TOTAL",
        "Origin": stops[0],
        "Destination": stops[-1],
        "Distance (NM)": round(total_distance, 2),
        "Duration (Days)": round(total_days, 2)
    }],
    itinerary=list(stops)
)
''',

    792: '''
export_voyage_results(
    "Multi-Leg",
    "Comparison",
    [
        {
            "Leg": row["Leg"],
            "Origin": row["Origin"],
            "Destination": row["Destination"],
            "Unrestricted (NM)": row["Unrestricted (NM)"],
            "Restricted (NM)": row["Restricted (NM)"],
            "Difference (NM)": row["Difference (NM)"]
        }
        for row in leg_results
    ],
    itinerary=list(stops)
)
''',

    957: '''
export_voyage_results(
    "Position-to-Port",
    "Standard",
    [{
        "Destination": destination["port_name"],
        "Distance (NM)": round(distance, 2),
        "Duration (Hours)": round(hours, 2),
        "Duration (Days)": round(days, 2)
    }],
    itinerary=[destination["port_name"]],
    vessel_position={
        "latitude": float(latitude),
        "longitude": float(longitude)
    }
)
''',

    1040: '''
export_voyage_results(
    "Position-to-Port",
    "Comparison",
    [
        {
            "Route": label,
            "Destination": destination["port_name"],
            "Distance (NM)": round(result["distance"], 2),
            "Duration (Days)": round(result["days"], 2)
        }
        for label, result in [
            ("Unrestricted", unrestricted),
            ("Restricted", restricted)
        ]
    ],
    itinerary=[destination["port_name"]],
    vessel_position={
        "latitude": float(latitude),
        "longitude": float(longitude)
    }
)
'''
}

# ------------------------------------------------------------
# 3. INSERT EXPORTS AFTER MAP DISPLAY BLOCKS
# ------------------------------------------------------------

lines = original_code.splitlines(keepends=True)

map_locations = [
    i for i, line in enumerate(lines)
    if "_repr_html_" in line
]

expected_lines = [414, 495, 678, 792, 957, 1040]
actual_lines = [i + 1 for i in map_locations]

if actual_lines != expected_lines:
    raise ValueError(
        f"Map locations have changed. Found: {actual_lines}. "
        "No changes were made."
    )

for line_number in sorted(export_blocks.keys(), reverse=True):

    index = line_number - 1

    # Find the closing parenthesis of the html() call
    closing_index = index + 1

    while closing_index < len(lines):
        if lines[closing_index].strip() == ")":
            break
        closing_index += 1

    if closing_index >= len(lines):
        raise ValueError(
            f"Could not find map display closing bracket near line {line_number}."
        )

    # Match indentation of the html() statement
    html_line_index = index - 1

    indentation = (
        len(lines[html_line_index])
        - len(lines[html_line_index].lstrip())
    )

    block = textwrap.indent(
        textwrap.dedent(export_blocks[line_number]).strip(),
        " " * indentation
    )

    lines.insert(
        closing_index + 1,
        "\n\n" + block + "\n"
    )

updated_code = "".join(lines)

# ------------------------------------------------------------
# 4. INSERT SHARED EXPORT FUNCTIONS
# ------------------------------------------------------------

tabs_marker = "# APPLICATION TABS"

if tabs_marker not in updated_code:
    raise ValueError("Application tabs marker not found.")

marker_index = updated_code.index(tabs_marker)

updated_code = (
    updated_code[:marker_index]
    + export_functions
    + "\n"
    + updated_code[marker_index:]
)

# ------------------------------------------------------------
# 5. ADD JSON IMPORT
# ------------------------------------------------------------

if "import json\n" not in updated_code:
    updated_code = "import json\n" + updated_code

# ------------------------------------------------------------
# 6. VALIDATE AND SAVE
# ------------------------------------------------------------

compile(updated_code, "app.py", "exec")

backup_path = Path("app_before_exports.py")

shutil.copy2(app_path, backup_path)

app_path.write_text(
    updated_code,
    encoding="utf-8"
)

print("SUCCESS: CSV and JSON exports installed!")
print("Backup saved as:", backup_path)
print("All six export locations updated.")

SUCCESS: CSV and JSON exports installed!
Backup saved as: app_before_exports.py
All six export locations updated.

In [107]:
from pathlib import Path
import shutil

# ============================================================
# STEP 8A — SHARED INPUT VALIDATION
# ============================================================

app_path = Path("app.py")
app_code = app_path.read_text(encoding="utf-8")

validation_marker = "# VALIDATION FUNCTIONS — STEP 8A"

if validation_marker in app_code:
    raise ValueError(
        "Validation functions are already installed."
    )

validation_functions = '''
# ============================================================
# VALIDATION FUNCTIONS — STEP 8A
# ============================================================

import math


def validate_coordinates(longitude, latitude):
    """Validate longitude and latitude values."""

    try:
        longitude = float(longitude)
        latitude = float(latitude)
    except (TypeError, ValueError):
        raise ValueError(
            "Longitude and latitude must be numeric values."
        )

    if not math.isfinite(longitude) or not math.isfinite(latitude):
        raise ValueError(
            "Longitude and latitude must be finite numbers."
        )

    if not -180 <= longitude <= 180:
        raise ValueError(
            "Longitude must be between -180 and 180 degrees."
        )

    if not -90 <= latitude <= 90:
        raise ValueError(
            "Latitude must be between -90 and 90 degrees."
        )

    return [longitude, latitude]


def validate_speed(vessel_speed):
    """Ensure vessel speed is valid."""

    try:
        vessel_speed = float(vessel_speed)
    except (TypeError, ValueError):
        raise ValueError(
            "Vessel speed must be a numeric value."
        )

    if not math.isfinite(vessel_speed) or vessel_speed <= 0:
        raise ValueError(
            "Vessel speed must be greater than zero."
        )

    return vessel_speed


def validate_route_result(route):
    """Check that the routing engine returned a usable route."""

    if route is None:
        raise ValueError(
            "The routing engine did not return a route."
        )

    if not hasattr(route, "properties"):
        raise ValueError(
            "The routing engine returned an invalid route."
        )

    distance = float(route.properties["length"])

    if not math.isfinite(distance) or distance <= 0:
        raise ValueError(
            "The calculated route distance must be greater than zero."
        )

    geometry = route.geometry

    if not geometry or not geometry.get("coordinates"):
        raise ValueError(
            "The routing engine returned no route coordinates."
        )

    coordinates = geometry["coordinates"]

    if len(coordinates) < 2:
        raise ValueError(
            "The calculated route contains insufficient coordinates."
        )

    for coordinate in coordinates:
        if len(coordinate) < 2:
            raise ValueError(
                "The route contains an invalid coordinate."
            )

        validate_coordinates(
            coordinate[0],
            coordinate[1]
        )

    return distance


def validate_itinerary(stops):
    """Validate a multi-leg voyage itinerary."""

    if len(stops) < 2:
        raise ValueError(
            "A multi-leg voyage requires at least two ports."
        )

    for index in range(len(stops) - 1):
        if stops[index] == stops[index + 1]:
            raise ValueError(
                "Consecutive duplicate ports are not allowed."
            )

    return True
'''

# Insert before the application tabs
tabs_marker = "# APPLICATION TABS"

if tabs_marker not in app_code:
    raise ValueError(
        "Application tabs marker not found. "
        "No changes were made."
    )

marker_index = app_code.index(tabs_marker)

updated_code = (
    app_code[:marker_index]
    + validation_functions
    + "\n"
    + app_code[marker_index:]
)

# Check syntax before saving
compile(updated_code, "app.py", "exec")

# Create backup
backup_path = Path("app_before_validation.py")
shutil.copy2(app_path, backup_path)

# Save updated application
app_path.write_text(
    updated_code,
    encoding="utf-8"
)

print("SUCCESS: Validation functions installed!")
print("Backup saved as:", backup_path)

SUCCESS: Validation functions installed!
Backup saved as: app_before_validation.py

In [109]:
from pathlib import Path
import shutil

# ============================================================
# STEP 8A.3 — INTEGRATE VALIDATION
# ============================================================

app_path = Path("app.py")
app_code = app_path.read_text(encoding="utf-8")

marker = "# VALIDATION INTEGRATION — STEP 8A.3"

if marker in app_code:
    raise ValueError(
        "Validation integration is already installed."
    )

# ------------------------------------------------------------
# 1. VALIDATE ALL SEAROUTE CALLS
# ------------------------------------------------------------

# Locate every call to the routing engine.
# Replace the routing function with a validated wrapper.
# This preserves the existing route calculations.

validation_wrapper = '''
# ============================================================
# VALIDATION INTEGRATION — STEP 8A.3
# ============================================================

_original_searoute = sr.searoute


def validated_searoute(origin, destination, *args, **kwargs):
    """Validate inputs and results for every searoute calculation."""

    if len(origin) < 2 or len(destination) < 2:
        raise ValueError(
            "Origin and destination must contain longitude and latitude."
        )

    origin = validate_coordinates(origin[0], origin[1])
    destination = validate_coordinates(destination[0], destination[1])

    validate_speed(speed)

    if origin == destination:
        raise ValueError(
            "Origin and destination coordinates must be different."
        )

    try:
        route = _original_searoute(
            origin,
            destination,
            *args,
            **kwargs
        )
    except Exception as error:
        raise ValueError(
            f"The routing engine could not calculate this voyage: {error}"
        ) from error

    validate_route_result(route)

    return route


sr.searoute = validated_searoute
'''

# ------------------------------------------------------------
# 2. INSERT WRAPPER BEFORE APPLICATION TABS
# ------------------------------------------------------------

tabs_marker = "# APPLICATION TABS"

if tabs_marker not in app_code:
    raise ValueError(
        "Application tabs marker not found. "
        "No changes were made."
    )

marker_index = app_code.index(tabs_marker)

updated_code = (
    app_code[:marker_index]
    + validation_wrapper
    + "\n"
    + app_code[marker_index:]
)

# ------------------------------------------------------------
# 3. VALIDATE MULTI-LEG ITINERARIES
# ------------------------------------------------------------

# Insert validation immediately after retrieving voyage stops.

old_stops = '''stops = st.session_state.voyage_stops'''

new_stops = '''stops = st.session_state.voyage_stops
                validate_itinerary(stops)'''

# There should be two occurrences:
# Standard Multi-Leg and Multi-Leg Comparison.

occurrences = updated_code.count(old_stops)

if occurrences != 2:
    raise ValueError(
        f"Expected 2 Multi-Leg itinerary handlers, found {occurrences}. "
        "No changes were made."
    )

updated_code = updated_code.replace(
    old_stops,
    new_stops
)

# ------------------------------------------------------------
# 4. VALIDATE PYTHON SYNTAX
# ------------------------------------------------------------

compile(updated_code, "app.py", "exec")

# ------------------------------------------------------------
# 5. BACKUP AND SAVE
# ------------------------------------------------------------

backup_path = Path("app_before_validation_integration.py")

shutil.copy2(app_path, backup_path)

app_path.write_text(
    updated_code,
    encoding="utf-8"
)

print("SUCCESS: Validation integrated into routing operations!")
print("Backup saved as:", backup_path)
print("Routing calls now use validated_searoute().")
print("Multi-Leg itinerary validation enabled.")

SUCCESS: Validation integrated into routing operations!
Backup saved as: app_before_validation_integration.py
Routing calls now use validated_searoute().
Multi-Leg itinerary validation enabled.

In [111]:
from pathlib import Path
import shutil

# ============================================================
# FIX — REMOVE RECURSIVE SEAROUTE WRAPPER
# ============================================================

app_path = Path("app.py")
app_code = app_path.read_text(encoding="utf-8")

start_marker = (
    "# ============================================================\n"
    "# VALIDATION INTEGRATION — STEP 8A.3\n"
    "# ============================================================\n"
)

end_marker = "# APPLICATION TABS"

if start_marker not in app_code:
    raise ValueError(
        "Validation wrapper not found. No changes were made."
    )

if end_marker not in app_code:
    raise ValueError(
        "Application tabs marker not found. No changes were made."
    )

start_index = app_code.index(start_marker)
end_index = app_code.index(end_marker, start_index)

# Remove the problematic wrapper
updated_code = (
    app_code[:start_index]
    + app_code[end_index:]
)

# Validate Python syntax
compile(updated_code, "app.py", "exec")

# Create backup
backup_path = Path("app_before_wrapper_fix.py")
shutil.copy2(app_path, backup_path)

# Save corrected application
app_path.write_text(
    updated_code,
    encoding="utf-8"
)

print("SUCCESS: Recursive routing wrapper removed!")
print("Backup saved as:", backup_path)

SUCCESS: Recursive routing wrapper removed!
Backup saved as: app_before_wrapper_fix.py

In [113]:
from pathlib import Path

app_code = Path("app.py").read_text(encoding="utf-8")
lines = app_code.splitlines()

print("STREAMLIT CALCULATION HANDLERS")
print("=" * 60)

for i, line in enumerate(lines):

    if "if st.button(" in line:

        print(f"\nButton handler found at line {i + 1}")

        start = max(0, i - 2)
        end = min(len(lines), i + 8)

        for j in range(start, end):
            print(f"{j + 1}: {lines[j]}")

STREAMLIT CALCULATION HANDLERS
============================================================

Button handler found at line 549
547:     )
548:
549:     if st.button("Calculate Route", key="calculate_port"):
550:
551:         try:
552:
553:             if origin_name == destination_name:
554:                 st.error(
555:                     "Origin and destination ports must be different."
556:                 )

Button handler found at line 622
620:     # --------------------------------------------------------
621:
622:     if st.button("Compare Routes", key="compare_port"):
623:
624:         try:
625:
626:             if not restrictions:
627:                 st.warning(
628:                     "Select a passage restriction before comparing routes."
629:                 )

Button handler found at line 745
743:
744:     with col1:
745:         if st.button("Add Stop", key="add_stop"):
746:             if (
747:                 st.session_state.voyage_stops
748:                 and st.session_state.voyage_stops[-1] == selected_stop
749:             ):
750:                 st.warning("Consecutive duplicate ports are not allowed.")
751:             else:
752:                 st.session_state.voyage_stops.append(selected_stop)

Button handler found at line 755
753:
754:     with col2:
755:         if st.button("Remove Last Stop", key="remove_stop"):
756:             if st.session_state.voyage_stops:
757:                 st.session_state.voyage_stops.pop()
758:
759:     with col3:
760:         if st.button("Clear Itinerary", key="clear_stops"):
761:             st.session_state.voyage_stops = []
762:

Button handler found at line 760
758:
759:     with col3:
760:         if st.button("Clear Itinerary", key="clear_stops"):
761:             st.session_state.voyage_stops = []
762:
763:     # Display itinerary
764:     st.subheader("Current Itinerary")
765:
766:     if st.session_state.voyage_stops:
767:         for index, port in enumerate(

Button handler found at line 776
774:
775:     # Calculate multi-leg voyage
776:     if st.button(
777:         "Calculate Multi-Leg Voyage",
778:         key="calculate_multi"
779:     ):
780:
781:         if len(st.session_state.voyage_stops) < 2:
782:             st.error("Please add at least two ports.")
783:

Button handler found at line 929
927:     # --------------------------------------------------------
928:
929:     if st.button("Compare Multi-Leg Routes", key="compare_multi"):
930:
931:         if len(st.session_state.voyage_stops) < 2:
932:
933:             st.error("Please add at least two ports.")
934:
935:         elif not restrictions:
936:

Button handler found at line 1097
1095:     )
1096:
1097:     if st.button(
1098:         "Calculate Position-to-Port Route",
1099:         key="calculate_position"
1100:     ):
1101:
1102:         try:
1103:
1104:             destination = port_options[

Button handler found at line 1246
1244:     # --------------------------------------------------------
1245:
1246:     if st.button("Compare Routes", key="compare_position"):
1247:
1248:         try:
1249:
1250:             if not restrictions:
1251:
1252:                 st.warning(
1253:                     "Select a passage restriction before comparing routes."

In [115]:
from pathlib import Path

lines = Path("app.py").read_text(encoding="utf-8").splitlines()

sections = {
    "Port-to-Port Calculation": (549, 621),
    "Port-to-Port Comparison": (622, 720),
    "Multi-Leg Calculation": (776, 928),
    "Multi-Leg Comparison": (929, 1040),
    "Position-to-Port Calculation": (1097, 1245),
    "Position-to-Port Comparison": (1246, len(lines))
}

for name, (start, end) in sections.items():

    print("\n" + "=" * 70)
    print(name)
    print("=" * 70)

    for line_number in range(start, min(end, len(lines)) + 1):
        print(f"{line_number}: {lines[line_number - 1]}")

======================================================================
Port-to-Port Calculation
======================================================================
549:     if st.button("Calculate Route", key="calculate_port"):
550:
551:         try:
552:
553:             if origin_name == destination_name:
554:                 st.error(
555:                     "Origin and destination ports must be different."
556:                 )
557:
558:             else:
559:
560:                 origin = port_options[origin_name]
561:                 destination = port_options[destination_name]
562:
563:                 route, distance, hours, days = calculate_route(
564:                     origin,
565:                     destination
566:                 )
567:
568:                 st.success("Route calculated successfully!")
569:
570:                 col1, col2, col3 = st.columns(3)
571:
572:                 col1.metric(
573:                     "Maritime Distance",
574:                     f"{distance:,.2f} NM"
575:                 )
576:
577:                 col2.metric(
578:                     "Sailing Time",
579:                     f"{hours:,.2f} hours"
580:                 )
581:
582:                 col3.metric(
583:                     "Sailing Duration",
584:                     f"{days:,.2f} days"
585:                 )
586:
587:                 voyage_map = create_route_map(
588:                     route,
589:                     origin,
590:                     destination
591:                 )
592:
593:                 html(
594:                     voyage_map._repr_html_(),
595:                     height=550
596:                 )
597:
598:
599:                 export_voyage_results(
600:                     "Port-to-Port",
601:                     "Standard",
602:                     [{
603:                         "Origin": origin["port_name"],
604:                         "Destination": destination["port_name"],
605:                         "Distance (NM)": round(distance, 2),
606:                         "Duration (Hours)": round(hours, 2),
607:                         "Duration (Days)": round(days, 2)
608:                     }],
609:                     itinerary=[origin["port_name"], destination["port_name"]]
610:                 )
611:
612:         except Exception as error:
613:
614:             st.error(f"Route calculation failed: {error}")
615:
616:
617:
618:     # --------------------------------------------------------
619:     # PORT-TO-PORT ROUTE COMPARISON
620:     # --------------------------------------------------------
621:

======================================================================
Port-to-Port Comparison
======================================================================
622:     if st.button("Compare Routes", key="compare_port"):
623:
624:         try:
625:
626:             if not restrictions:
627:                 st.warning(
628:                     "Select a passage restriction before comparing routes."
629:                 )
630:
631:             elif origin_name == destination_name:
632:                 st.error(
633:                     "Origin and destination ports must be different."
634:                 )
635:
636:             else:
637:
638:                 origin = port_options[origin_name]
639:                 destination = port_options[destination_name]
640:
641:                 start_coordinates = get_coordinates(origin)
642:                 end_coordinates = get_coordinates(destination)
643:
644:                 unrestricted = calculate_comparison_route(
645:                     start_coordinates,
646:                     end_coordinates,
647:                     []
648:                 )
649:
650:                 restricted = calculate_comparison_route(
651:                     start_coordinates,
652:                     end_coordinates,
653:                     restrictions
654:                 )
655:
656:                 st.success("Routes compared successfully!")
657:
658:                 display_comparison_results(
659:                     [unrestricted],
660:                     [restricted]
661:                 )
662:
663:                 markers = [
664:                     {
665:                         "location": [
666:                             float(origin["approach_latitude"]),
667:                             float(origin["approach_longitude"])
668:                         ],
669:                         "name": origin["port_name"],
670:                         "color": "green"
671:                     },
672:                     {
673:                         "location": [
674:                             float(destination["approach_latitude"]),
675:                             float(destination["approach_longitude"])
676:                         ],
677:                         "name": destination["port_name"],
678:                         "color": "purple"
679:                     }
680:                 ]
681:
682:                 comparison_map = create_comparison_map(
683:                     [unrestricted],
684:                     [restricted],
685:                     markers
686:                 )
687:
688:                 html(
689:                     comparison_map._repr_html_(),
690:                     height=550
691:                 )
692:
693:
694:                 export_voyage_results(
695:                     "Port-to-Port",
696:                     "Comparison",
697:                     [
698:                         {
699:                             "Route": label,
700:                             "Origin": origin["port_name"],
701:                             "Destination": destination["port_name"],
702:                             "Distance (NM)": round(result["distance"], 2),
703:                             "Duration (Days)": round(result["days"], 2)
704:                         }
705:                         for label, result in [
706:                             ("Unrestricted", unrestricted),
707:                             ("Restricted", restricted)
708:                         ]
709:                     ],
710:                     itinerary=[origin["port_name"], destination["port_name"]]
711:                 )
712:
713:         except Exception as error:
714:
715:             st.error(f"Route comparison failed: {error}")
716:
717:
718: # ============================================================
719: # TAB 2 — MULTI-LEG
720: # ============================================================

======================================================================
Multi-Leg Calculation
======================================================================
776:     if st.button(
777:         "Calculate Multi-Leg Voyage",
778:         key="calculate_multi"
779:     ):
780:
781:         if len(st.session_state.voyage_stops) < 2:
782:             st.error("Please add at least two ports.")
783:
784:         else:
785:             try:
786:
787:                 stops = st.session_state.voyage_stops
788:                 validate_itinerary(stops)
789:
790:                 leg_results = []
791:                 all_coordinates = []
792:
793:                 total_distance = 0
794:
795:                 voyage_map = folium.Map(
796:                     location=[0, 0],
797:                     zoom_start=2
798:                 )
799:
800:                 route_colors = [
801:                     "blue", "red", "green",
802:                     "purple", "orange", "darkblue"
803:                 ]
804:
805:                 for i in range(len(stops) - 1):
806:
807:                     origin = port_options[stops[i]]
808:                     destination = port_options[stops[i + 1]]
809:
810:                     route, distance, hours, days = calculate_route(
811:                         origin,
812:                         destination
813:                     )
814:
815:                     total_distance += distance
816:
817:                     coordinates = [
818:                         [lat, lon]
819:                         for lon, lat in route.geometry["coordinates"]
820:                     ]
821:
822:                     all_coordinates.extend(coordinates)
823:
824:                     folium.PolyLine(
825:                         locations=coordinates,
826:                         color=route_colors[i % len(route_colors)],
827:                         weight=4,
828:                         tooltip=f"Leg {i + 1}: {distance:,.2f} NM"
829:                     ).add_to(voyage_map)
830:
831:                     leg_results.append({
832:                         "Leg": i + 1,
833:                         "Origin": origin["port_name"],
834:                         "Destination": destination["port_name"],
835:                         "Distance (NM)": round(distance, 2),
836:                         "Duration (Days)": round(days, 2)
837:                     })
838:
839:                 # Add port markers
840:                 for i, port_name in enumerate(stops):
841:
842:                     port = port_options[port_name]
843:
844:                     location = [
845:                         float(port["approach_latitude"]),
846:                         float(port["approach_longitude"])
847:                     ]
848:
849:                     marker_color = (
850:                         "green" if i == 0
851:                         else "purple" if i == len(stops) - 1
852:                         else "blue"
853:                     )
854:
855:                     folium.Marker(
856:                         location=location,
857:                         popup=f"Stop {i + 1}: {port['port_name']}",
858:                         icon=folium.Icon(color=marker_color)
859:                     ).add_to(voyage_map)
860:
861:                 total_hours = total_distance / speed
862:                 total_days = total_hours / 24
863:
864:                 st.success("Multi-leg voyage calculated successfully!")
865:
866:                 col1, col2, col3 = st.columns(3)
867:
868:                 col1.metric(
869:                     "Total Distance",
870:                     f"{total_distance:,.2f} NM"
871:                 )
872:
873:                 col2.metric(
874:                     "Total Sailing Time",
875:                     f"{total_hours:,.2f} hours"
876:                 )
877:
878:                 col3.metric(
879:                     "Total Sailing Duration",
880:                     f"{total_days:,.2f} days"
881:                 )
882:
883:                 st.subheader("Leg-by-Leg Breakdown")
884:
885:                 st.dataframe(
886:                     pd.DataFrame(leg_results),
887:                     use_container_width=True
888:                 )
889:
890:                 voyage_map.fit_bounds(all_coordinates)
891:
892:                 html(
893:                     voyage_map._repr_html_(),
894:                     height=550
895:                 )
896:
897:
898:                 export_voyage_results(
899:                     "Multi-Leg",
900:                     "Standard",
901:                     [
902:                         {
903:                             "Leg": row["Leg"],
904:                             "Origin": row["Origin"],
905:                             "Destination": row["Destination"],
906:                             "Distance (NM)": row["Distance (NM)"],
907:                             "Duration (Days)": row["Duration (Days)"]
908:                         }
909:                         for row in leg_results
910:                     ] + [{
911:                         "Leg": "TOTAL",
912:                         "Origin": stops[0],
913:                         "Destination": stops[-1],
914:                         "Distance (NM)": round(total_distance, 2),
915:                         "Duration (Days)": round(total_days, 2)
916:                     }],
917:                     itinerary=list(stops)
918:                 )
919:
920:             except Exception as error:
921:                 st.error(f"Multi-leg calculation failed: {error}")
922:
923:
924:
925:     # --------------------------------------------------------
926:     # MULTI-LEG ROUTE COMPARISON
927:     # --------------------------------------------------------
928:

======================================================================
Multi-Leg Comparison
======================================================================
929:     if st.button("Compare Multi-Leg Routes", key="compare_multi"):
930:
931:         if len(st.session_state.voyage_stops) < 2:
932:
933:             st.error("Please add at least two ports.")
934:
935:         elif not restrictions:
936:
937:             st.warning(
938:                 "Select a passage restriction before comparing routes."
939:             )
940:
941:         else:
942:
943:             try:
944:
945:                 stops = st.session_state.voyage_stops
946:                 validate_itinerary(stops)
947:
948:                 unrestricted_routes = []
949:                 restricted_routes = []
950:                 markers = []
951:                 leg_results = []
952:
953:                 for i in range(len(stops) - 1):
954:
955:                     origin = port_options[stops[i]]
956:                     destination = port_options[stops[i + 1]]
957:
958:                     start_coordinates = get_coordinates(origin)
959:                     end_coordinates = get_coordinates(destination)
960:
961:                     unrestricted = calculate_comparison_route(
962:                         start_coordinates,
963:                         end_coordinates,
964:                         []
965:                     )
966:
967:                     restricted = calculate_comparison_route(
968:                         start_coordinates,
969:                         end_coordinates,
970:                         restrictions
971:                     )
972:
973:                     unrestricted_routes.append(unrestricted)
974:                     restricted_routes.append(restricted)
975:
976:                     leg_results.append({
977:                         "Leg": i + 1,
978:                         "Origin": origin["port_name"],
979:                         "Destination": destination["port_name"],
980:                         "Unrestricted (NM)": round(
981:                             unrestricted["distance"], 2
982:                         ),
983:                         "Restricted (NM)": round(
984:                             restricted["distance"], 2
985:                         ),
986:                         "Difference (NM)": round(
987:                             restricted["distance"] - unrestricted["distance"],
988:                             2
989:                         )
990:                     })
991:
992:                 for i, port_name in enumerate(stops):
993:
994:                     port = port_options[port_name]
995:
996:                     markers.append({
997:                         "location": [
998:                             float(port["approach_latitude"]),
999:                             float(port["approach_longitude"])
1000:                         ],
1001:                         "name": f"Stop {i + 1}: {port['port_name']}",
1002:                         "color": (
1003:                             "green" if i == 0
1004:                             else "purple" if i == len(stops) - 1
1005:                             else "blue"
1006:                         )
1007:                     })
1008:
1009:                 st.success("Multi-leg routes compared successfully!")
1010:
1011:                 st.subheader("Leg-by-Leg Comparison")
1012:
1013:                 st.dataframe(
1014:                     pd.DataFrame(leg_results),
1015:                     use_container_width=True,
1016:                     hide_index=True
1017:                 )
1018:
1019:                 display_comparison_results(
1020:                     unrestricted_routes,
1021:                     restricted_routes
1022:                 )
1023:
1024:                 comparison_map = create_comparison_map(
1025:                     unrestricted_routes,
1026:                     restricted_routes,
1027:                     markers
1028:                 )
1029:
1030:                 html(
1031:                     comparison_map._repr_html_(),
1032:                     height=550
1033:                 )
1034:
1035:
1036:                 export_voyage_results(
1037:                     "Multi-Leg",
1038:                     "Comparison",
1039:                     [
1040:                         {

======================================================================
Position-to-Port Calculation
======================================================================
1097:     if st.button(
1098:         "Calculate Position-to-Port Route",
1099:         key="calculate_position"
1100:     ):
1101:
1102:         try:
1103:
1104:             destination = port_options[
1105:                 position_destination_name
1106:             ]
1107:
1108:             # searoute requires [longitude, latitude]
1109:             vessel_coordinates = [
1110:                 float(longitude),
1111:                 float(latitude)
1112:             ]
1113:
1114:             destination_coordinates = get_coordinates(
1115:                 destination
1116:             )
1117:
1118:             # Calculate maritime route
1119:             route = sr.searoute(
1120:                 vessel_coordinates,
1121:                 destination_coordinates,
1122:                 units="naut",
1123:                 restrictions=restrictions
1124:             )
1125:
1126:             distance = float(
1127:                 route.properties["length"]
1128:             )
1129:
1130:             if distance <= 0:
1131:                 raise ValueError(
1132:                     "No valid maritime route was returned."
1133:                 )
1134:
1135:             # Calculate sailing duration
1136:             hours = distance / speed
1137:             days = hours / 24
1138:
1139:             st.success(
1140:                 "Position-to-Port route calculated successfully!"
1141:             )
1142:
1143:             # Display results
1144:             col1, col2, col3 = st.columns(3)
1145:
1146:             col1.metric(
1147:                 "Maritime Distance",
1148:                 f"{distance:,.2f} NM"
1149:             )
1150:
1151:             col2.metric(
1152:                 "Sailing Time",
1153:                 f"{hours:,.2f} hours"
1154:             )
1155:
1156:             col3.metric(
1157:                 "Sailing Duration",
1158:                 f"{days:,.2f} days"
1159:             )
1160:
1161:             # Create interactive map
1162:             route_coordinates = [
1163:                 [lat, lon]
1164:                 for lon, lat in route.geometry["coordinates"]
1165:             ]
1166:
1167:             if not route_coordinates:
1168:                 raise ValueError(
1169:                     "No route coordinates were returned."
1170:                 )
1171:
1172:             voyage_map = folium.Map(
1173:                 location=[latitude, longitude],
1174:                 zoom_start=3
1175:             )
1176:
1177:             # Draw maritime route
1178:             folium.PolyLine(
1179:                 locations=route_coordinates,
1180:                 color="blue",
1181:                 weight=4,
1182:                 tooltip=f"Maritime Distance: {distance:,.2f} NM"
1183:             ).add_to(voyage_map)
1184:
1185:             # Vessel position marker
1186:             folium.Marker(
1187:                 location=[latitude, longitude],
1188:                 popup="Current Vessel Position",
1189:                 tooltip="Vessel Position",
1190:                 icon=folium.Icon(color="green")
1191:             ).add_to(voyage_map)
1192:

In [117]:
from pathlib import Path

lines = Path("app.py").read_text(encoding="utf-8").splitlines()

sections = {
    "Port-to-Port Calculation": (549, 621),
    "Port-to-Port Comparison": (622, 720),
    "Multi-Leg Calculation": (776, 928),
    "Multi-Leg Comparison": (929, 1040),
    "Position-to-Port Calculation": (1097, 1245),
    "Position-to-Port Comparison": (1246, len(lines))
}

output = []

for name, (start, end) in sections.items():
    output.append(f"\n{'=' * 70}\n{name}\n{'=' * 70}\n")

    for line_number in range(start, min(end, len(lines)) + 1):
        output.append(f"{line_number}: {lines[line_number - 1]}")

Path("routing_handlers.txt").write_text(
    "\n".join(output),
    encoding="utf-8"
)

print("SUCCESS: routing_handlers.txt created!")

SUCCESS: routing_handlers.txt created!

In [123]:
from pathlib import Path
import shutil

# STEP 8B — INSTALL RESULTS PERSISTENCE

app_path = Path("app.py")
updated_path = Path("app_persistent.py")
backup_path = Path("app_before_persistence.py")

if not app_path.exists():
    raise FileNotFoundError("Current app.py not found.")

if not updated_path.exists():
    raise FileNotFoundError(
        "app_persistent.py not found. "
        "Move the downloaded file into your project folder."
    )

updated_code = updated_path.read_text(encoding="utf-8")

# Validate before modifying the application
compile(updated_code, "app.py", "exec")

# Preserve the current working version
shutil.copy2(app_path, backup_path)

# Install the updated application
app_path.write_text(updated_code, encoding="utf-8")

print("SUCCESS: Results persistence installed!")
print("Backup saved as:", backup_path)

SUCCESS: Results persistence installed!
Backup saved as: app_before_persistence.py

In [125]:
from pathlib import Path

app_code = Path("app.py").read_text(encoding="utf-8")
lines = app_code.splitlines()

print("ERROR HANDLING AND SESSION STATE INSPECTION")
print("=" * 65)

keywords = [
    "except Exception",
    "st.error(",
    "st.warning(",
    "session_state",
    "persistent",
    "validate_route_result",
    "validate_coordinates",
    "validate_speed"
]

matches = []

for i, line in enumerate(lines):
    if any(keyword in line for keyword in keywords):
        matches.append(i)

# Group nearby matches to avoid printing the same lines repeatedly.
ranges = []

for i in matches:
    start = max(0, i - 2)
    end = min(len(lines), i + 4)

    if ranges and start <= ranges[-1][1]:
        ranges[-1] = (ranges[-1][0], max(ranges[-1][1], end))
    else:
        ranges.append((start, end))

output = []

for start, end in ranges:
    output.append("\n" + "-" * 65)

    for j in range(start, end):
        output.append(f"{j + 1}: {lines[j]}")

report = "\n".join(output)

Path("error_handling_inspection.txt").write_text(
    report,
    encoding="utf-8"
)

print("SUCCESS: Error handling inspection completed!")
print("Total matching lines:", len(matches))
print("Report saved as: error_handling_inspection.txt")

ERROR HANDLING AND SESSION STATE INSPECTION
=================================================================
SUCCESS: Error handling inspection completed!
Total matching lines: 52
Report saved as: error_handling_inspection.txt

In [127]:
from pathlib import Path
import shutil
import re

# ============================================================
# STEP 8C.2 — ERROR RECOVERY
# ============================================================

app_path = Path("app.py")

if not app_path.exists():
    raise FileNotFoundError("app.py not found.")

original_code = app_path.read_text(encoding="utf-8")

marker = "# ERROR RECOVERY — STEP 8C.2"

if marker in original_code:
    raise ValueError("Error recovery is already installed.")

# Map each error handler to its persistence key.
error_handlers = {
    "Route calculation failed:": "persist_calculate_port",
    "Route comparison failed:": "persist_compare_port",
    "Multi-leg calculation failed:": "persist_calculate_multi",
    "Multi-leg comparison failed:": "persist_compare_multi",
    "Position-to-Port calculation failed:": "persist_calculate_position",
    "Position-to-Port comparison failed:": "persist_compare_position"
}

updated_code = original_code

for error_message, state_key in error_handlers.items():

    # Find the exception handler associated with this message.
    pattern = (
        r"(?P<indent>^[ \t]*)except Exception as error:"
        r"(?P<body>[\s\S]*?)"
        + re.escape(error_message)
    )

    matches = list(
        re.finditer(
            pattern,
            updated_code,
            flags=re.MULTILINE
        )
    )

    if len(matches) != 1:
        raise ValueError(
            f"Could not uniquely identify handler: {error_message}. "
            "No changes were saved."
        )

    match = matches[0]
    indentation = match.group("indent")

    replacement = (
        f"{indentation}except Exception as error:\n"
        f"{indentation}    {marker}\n"
        f"{indentation}    st.session_state.pop("
        f'"{state_key}", None)\n'
    )

    updated_code = (
        updated_code[:match.start()]
        + replacement
        + updated_code[match.end() - len(match.group("body")):]
    )

# Validate Python syntax.
compile(updated_code, "app.py", "exec")

# Create backup.
backup_path = Path("app_before_error_recovery.py")
shutil.copy2(app_path, backup_path)

# Save updated application.
app_path.write_text(
    updated_code,
    encoding="utf-8"
)

print("SUCCESS: Error recovery installed!")
print("Backup saved as:", backup_path)

IndentationError: unindent does not match any outer indentation level (app.py, line 54)

In [129]:
from pathlib import Path

app_path = Path("app.py")

try:
    compile(
        app_path.read_text(encoding="utf-8"),
        str(app_path),
        "exec"
    )
    print("SUCCESS: Your existing app.py is valid and unchanged.")
except SyntaxError as error:
    print("ERROR:", error)

SUCCESS: Your existing app.py is valid and unchanged.

In [131]:
from pathlib import Path
import shutil
import re

# ============================================================
# STEP 8C.2 — SAFE ERROR RECOVERY INSTALLATION
# ============================================================

app_path = Path("app.py")
original_code = app_path.read_text(encoding="utf-8")

marker = "# ERROR RECOVERY — STEP 8C.2"

if marker in original_code:
    raise ValueError("Error recovery is already installed.")

# Each error message corresponds to one routing operation.
error_handlers = {
    "Route calculation failed:": "persist_calculate_port",
    "Route comparison failed:": "persist_compare_port",
    "Multi-leg calculation failed:": "persist_calculate_multi",
    "Multi-leg comparison failed:": "persist_compare_multi",
    "Position-to-Port calculation failed:": "persist_calculate_position",
    "Position-to-Port comparison failed:": "persist_compare_position"
}

lines = original_code.splitlines(keepends=True)
insertions = []

# ------------------------------------------------------------
# 1. IDENTIFY EXACT EXCEPTION HANDLERS
# ------------------------------------------------------------

for error_message, state_key in error_handlers.items():

    matches = [
        i for i, line in enumerate(lines)
        if error_message in line
    ]

    if len(matches) != 1:
        raise ValueError(
            f"Expected one occurrence of '{error_message}', "
            f"found {len(matches)}. No changes were made."
        )

    error_line_index = matches[0]

    # Search backward for the nearest exception handler.
    except_index = None

    for i in range(error_line_index - 1, -1, -1):

        if re.match(
            r"^\s*except Exception as error:\s*$",
            lines[i]
        ):
            except_index = i
            break

    if except_index is None:
        raise ValueError(
            f"Exception handler not found for {error_message}."
        )

    # Preserve the original indentation.
    except_line = lines[except_index]

    indentation = (
        except_line[:len(except_line) - len(except_line.lstrip())]
    )

    insertion = (
        f"{indentation}    {marker}\n"
        f'{indentation}    st.session_state.pop("{state_key}", None)\n'
    )

    insertions.append((except_index + 1, insertion))

# Ensure each error message maps to a different exception handler.
positions = [position for position, _ in insertions]

if len(positions) != len(set(positions)):
    raise ValueError(
        "Multiple error messages matched the same exception handler. "
        "No changes were made."
    )

# ------------------------------------------------------------
# 2. INSERT ERROR RECOVERY STATEMENTS
# ------------------------------------------------------------

# Insert from bottom to top so line positions remain valid.
for position, insertion in sorted(
    insertions,
    reverse=True
):
    lines.insert(position, insertion)

updated_code = "".join(lines)

# ------------------------------------------------------------
# 3. VALIDATE BEFORE SAVING
# ------------------------------------------------------------

compile(updated_code, "app.py", "exec")

# Verify all six persistence keys were inserted.
for state_key in error_handlers.values():

    expected = (
        f'st.session_state.pop("{state_key}", None)'
    )

    if expected not in updated_code:
        raise ValueError(
            f"Missing error recovery for {state_key}."
        )

# ------------------------------------------------------------
# 4. BACKUP AND SAVE
# ------------------------------------------------------------

backup_path = Path("app_before_error_recovery.py")

shutil.copy2(app_path, backup_path)

app_path.write_text(
    updated_code,
    encoding="utf-8"
)

print("SUCCESS: Error recovery installed!")
print("Backup saved as:", backup_path)
print("All six routing error handlers updated.")

SUCCESS: Error recovery installed!
Backup saved as: app_before_error_recovery.py
All six routing error handlers updated.